src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CPID_from_OSCAR__c</fullName>
        <description>This is an external id that will be used for the data upload process.</description>
        <externalId>true</externalId>
        <inlineHelpText>Counter-Party Identifier Code (CPID). The Treasury produced a list of all bodies within the Whole of Government Accounts boundary (WGA). Each WGA body is issued by the Treasury with a unique CPID code. To be provided if applicable.</inlineHelpText>
        <label>CPID (from OSCAR)</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Intermediary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Intermediary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VAT_Reg_no__c</fullName>
        <description>This is an external id that will be used for the data upload process.</description>
        <externalId>true</externalId>
        <inlineHelpText>Tax registration number. To be provided if applicable.</inlineHelpText>
        <label>VAT Reg no</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/COFOG_L2__c.object
<CustomObject>
    <fields>
        <fullName>COFOG_L2_Long_Name__c</fullName>
        <label>COFOG L2 Long Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>COFOG L2</label>
    <nameField>
        <label>COFOG L2 Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>COFOG L2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CSV_Upload__c.object
<CustomObject>
    <description>This is the object that saves the CSV upload attempts by super users.</description>
    <label>Data Upload</label>
    <nameField>
        <displayFormat>CSVU-{0000000}</displayFormat>
        <label>FileUpload Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Uploads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Grant_Award__c.object
<CustomObject>
    <fields>
        <fullName>Grant_Award_Name__c</fullName>
        <description>Description type - This is for users</description>
        <inlineHelpText>A Grant Award can be given to an Organisation (where a named Recipient is required and only one per Awards) or multiple Individuals (only total no of recipients is required). All grant awards need to have a Scheme created first.</inlineHelpText>
        <label>Grant Award Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Grant_Scheme__c</fullName>
        <description>This is the parent scheme for this award</description>
        <inlineHelpText>This is the System Scheme Reference No and clicking it will take you back to the Scheme that this award belong to.</inlineHelpText>
        <label>Grant Scheme</label>
        <referenceTo>Grant_Scheme__c</referenceTo>
        <relationshipLabel>Grant Awards</relationshipLabel>
        <relationshipName>Grant_Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Recipient_Secondary_Country__c</fullName>
        <inlineHelpText>If a grant award is going to a different address than the one alreday stored for the Recipient Organisation, then populate the country of the organisation&apos;s address.</inlineHelpText>
        <label>Recipient Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abu Dhabi</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Ajman</fullName>
                </value>
                <value>
                    <fullName>Akrotiri</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Ascension</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Baker Island</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant Award</label>
    <nameField>
        <displayFormat>GA-{000000}</displayFormat>
        <label>System Award Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Grant_Scheme__c.object
<CustomObject>
    <fields>
        <fullName>COFOG_L2__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the related COFOG L2 Code for this Scheme.</description>
        <inlineHelpText>Classification of the Functions of Government - values, levels 1 and 2, are taken from the United Nations Statistics Division classification published at unstats.un.org</inlineHelpText>
        <label>COFOG L2</label>
        <referenceTo>COFOG_L2__c</referenceTo>
        <relationshipLabel>Grant Schemes</relationshipLabel>
        <relationshipName>Grant_Schemes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheme_Reference_No__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is a reference number that can be given from a department&apos;s own internal system, should you wish to. It is optional &amp; will help reconciliation between GGIS &amp; your own system, but you don&apos;t have to include one.</inlineHelpText>
        <label>Scheme Reference No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Grant Scheme</label>
    <nameField>
        <displayFormat>SCH-{000000000}</displayFormat>
        <label>System Scheme Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Intermediary__c.object
<CustomObject>
    <description>This is the organisation which carries out the intermediary role</description>
    <fields>
        <fullName>Grant_Award_Name__c</fullName>
        <formula>HYPERLINK(
 IF(
  ISPICKVAL($Profile.UserType, &apos;PowerCustomerSuccess&apos;), 
  &apos;/datasolution/&apos;, &apos;/&apos;
  ) &amp;  Id, 
   Grant_Award__r.Grant_Award_Name__c , &apos;_self&apos;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Grant Award Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grant_Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the related grant award for this intermediary record</description>
        <label>System Award Reference No</label>
        <referenceTo>Grant_Award__c</referenceTo>
        <relationshipLabel>Intermediaries</relationshipLabel>
        <relationshipName>Intermediaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant_Scheme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the related grant scheme</description>
        <label>System Scheme Reference No</label>
        <referenceTo>Grant_Scheme__c</referenceTo>
        <relationshipLabel>Intermediaries</relationshipLabel>
        <relationshipName>Intermediaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intermediary_Organisation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Related organisation for this intermediary</description>
        <inlineHelpText>Organisations who distribute or administer grants on behalf of a government department i.e. a government agency, NDPB, charity or business. In some cases, a government department can act as an intermediary for another government department.</inlineHelpText>
        <label>Intermediary Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Intermediaries</relationshipLabel>
        <relationshipName>Intermediaries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>The intermediary role carried out by the organisation</description>
        <inlineHelpText>The role that an intermediary plays in the grant administration process. You can choose multiple roles.</inlineHelpText>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Market Engagement Advertising</fullName>
                </value>
                <value>
                    <fullName>Application Assessment</fullName>
                </value>
                <value>
                    <fullName>Due Diligence</fullName>
                </value>
                <value>
                    <fullName>Grant Award</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Performance Monitoring</fullName>
                </value>
                <value>
                    <fullName>Final Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Evaluation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Intermediary</label>
    <nameField>
        <displayFormat>INT-{00000000}</displayFormat>
        <label>Intermediary Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intermediaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Cabinet office backup/src/classes/CSVUploadSObjectFactoryTest.cls
/******************************************************************************************
@Author         Hamed Izadpanah
@Date           03/10/2015
@Project        Cloud Sherpas Cabinet Office Data Source
@Description    This is the unit test class for SObject factory class
*******************************************************************************************/
@isTest
private class CSVUploadSObjectFactoryTest {

    @testSetup()
    private static void setupTestData() {
        
        insert new CoA_L5__c(
            Name = '11111000'
        );
        TestDataFactory testFactory = new TestDataFactory();
        insert testFactory.createDefaultCSVColumnMappingItems();
        COFOG_L2__c newCOFOG = new COFOG_L2__c(
            Name = '123',
            COFOG_L2_Long_Name__c = 'RT'
        );
        insert newCOFOG;
        Account funderAccount = testFactory.createAccount('New Funder', 'FUN123');
        Account testDepartment = testFactory.createAccount('My New Department', 'DEP123');
        insert new List<Account> {funderAccount, testDepartment};
        User testSuperUser = testFactory.setupBasicUser(testDepartment, 'Super User 0', Constant.PROFILE_COMMUNITY_SUPER_USER);
        System.runAs(testSuperUser) {
            Grant_Scheme__c newGrantScheme = testFactory.createGrantScheme(funderAccount, 'New Scheme', newCOFOG);
            newGrantScheme.Scheme_Reference_No__c = 'MySchemeRefNumber';
            insert newGrantScheme;
        }
    }

    static Account testDepartment;
    static Account funderAccount;
    static COFOG_L2__c newCOFOG;
    static CSVUploadMapping grantAwardMapping;
    static void initData() {
        TestDataFactory testFactory = new TestDataFactory();
        CSV_Upload__c grantAwardCsvUpload = testFactory.createOrganisationGrantAwardCSVUpload(Constant.CSV_UPLOAD_CREATE_AWARD_TYPE);
        grantAwardMapping = new CSVUploadMapping(grantAwardCsvUpload);
        testDepartment = [SELECT Id FROM Account WHERE CPID_from_OSCAR__c = 'DEP123' LIMIT 1][0];
        funderAccount = [SELECT Id FROM Account WHERE CPID_from_OSCAR__c = 'FUN123' LIMIT 1][0];
        newCOFOG = [SELECT Id FROM COFOG_L2__c WHERE Name = '123' LIMIT 1][0];
    }

    @isTest
    static void testCreateNewGrantAwardFull() {
        /**
        initData();
        TestDataFactory testFactory = new TestDataFactory();
        User testSuperUser = testFactory.setupBasicUser(testDepartment, 'Super User 1', Constant.PROFILE_COMMUNITY_SUPER_USER);
        System.runAs(testSuperUser) {
            List<List<String>> allGrantAwardData = testFactory.createDefaultGrantAwardDataParsedCSV();
            CSVUploadSObjectFactory sobjectFactory = new CSVUploadSObjectFactory.CreateAwardsFactory();
            sobjectFactory.setCSVMapping(grantAwardMapping);
            CSVDocument csvDocumentToUse = new CSVDocument(allGrantAwardData);
            System.assertEquals(0, [SELECT COUNT() FROM Grant_Award__c]);
            System.assertEquals(0, [SELECT COUNT() FROM Account WHERE Name = 'This is a new recepient!']);
            System.assertEquals(0, [SELECT COUNT() FROM Intermediary__c]);
            sobjectFactory.build(csvDocumentToUse.allRows[0]);
            System.assertEquals(1, [SELECT COUNT() FROM Account WHERE Name = 'This is a new recepient!']);
            System.assertEquals(1, [SELECT COUNT() FROM Grant_Award__c]);
            System.assertEquals(1, [
                                    SELECT COUNT()
                                    FROM Intermediary__c
                                    WHERE Intermediary_Organisation__r.Name = :TestDataFactory.NEW_INTERMEDIARY_1_NAME
                                            AND Role__c = :TestDataFactory.NEW_INTERMEDIARY_1_ROLE
                                                    AND Intermediary_Organisation__r.VAT_Reg_no__c = :TestDataFactory.NEW_INTERMEDIARY_1_ORGANISATION_ID
                                ]);
            System.assertEquals(1, [
                                    SELECT COUNT()
                                    FROM Intermediary__c
                                    WHERE Intermediary_Organisation__r.Name = :TestDataFactory.NEW_INTERMEDIARY_2_NAME
                                            AND Role__c = :TestDataFactory.NEW_INTERMEDIARY_2_ROLE
                                                    AND Intermediary_Organisation__r.VAT_Reg_no__c = :TestDataFactory.NEW_INTERMEDIARY_2_ORGANISATION_ID
                                ]);
        } **/
    }

    @isTest
    static void testCreateNewGrantAwardWithoutIntermediary() {
    /**
        initData();
        TestDataFactory testFactory = new TestDataFactory();
        User testSuperUser = testFactory.setupBasicUser(testDepartment, 'Super User 1', Constant.PROFILE_COMMUNITY_SUPER_USER);
        System.runAs(testSuperUser) {
            TestDataFactory.DEFAULT_GRANT_AWARD_DATA_PARSED.put(TestDataFactory.TEST_INTERMEDIARY1_ID_COLUMN, '');
            TestDataFactory.DEFAULT_GRANT_AWARD_DATA_PARSED.put(TestDataFactory.TEST_INTERMEDIARY2_ID_COLUMN, '');
            List<List<String>> allGrantAwardData = testFactory.createDefaultGrantAwardDataParsedCSV();
            CSVUploadSObjectFactory sobjectFactory = new CSVUploadSObjectFactory.CreateAwardsFactory();
            sobjectFactory.setCSVMapping(grantAwardMapping);
            CSVDocument csvDocumentToUse = new CSVDocument(allGrantAwardData);
            System.assertEquals(0, [SELECT COUNT() FROM Grant_Award__c]);
            System.assertEquals(0, [SELECT COUNT() FROM Account WHERE Name = 'This is a new recepient!']);
            System.assertEquals(0, [SELECT COUNT() FROM Intermediary__c]);
            sobjectFactory.build(csvDocumentToUse.allRows[0]);
            System.assertEquals(1, [SELECT COUNT() FROM Account WHERE Name = 'This is a new recepient!']);
            System.assertEquals(1, [SELECT COUNT() FROM Grant_Award__c]);
            System.assertEquals(0, [SELECT COUNT() FROM Intermediary__c]);
        }**/
    }

    @isTest
    static void testInvalidInsertGrantAwardNoNameAndRecepientId() {
        initData();
        TestDataFactory testFactory = new TestDataFactory();
        User testSuperUser = testFactory.setupBasicUser(testDepartment, 'Super User 1', Constant.PROFILE_COMMUNITY_SUPER_USER);
        System.runAs(testSuperUser) {

            TestDataFactory.DEFAULT_GRANT_AWARD_DATA_PARSED.put(TestDataFactory.TEST_GRANT_AWARD_NAME_COLUMN, '');
            TestDataFactory.DEFAULT_GRANT_AWARD_DATA_PARSED.put(TestDataFactory.TEST_RECEPIENT_ID_COLUMN, '');
            List<List<String>> allGrantAwardData = testFactory.createDefaultGrantAwardDataParsedCSV();
            CSVUploadSObjectFactory sobjectFactory = new CSVUploadSObjectFactory.CreateAwardsFactory();
            sobjectFactory.setCSVMapping(grantAwardMapping);
            CSVDocument csvDocumentToUse = new CSVDocument(allGrantAwardData);
            System.assertEquals(0, [SELECT COUNT() FROM Account WHERE Name = 'This is a new recepient!']);
            System.assertEquals(0, [SELECT COUNT() FROM Grant_Award__c]);
            System.assertEquals(0, [SELECT COUNT() FROM Intermediary__c]);
            try {
                sobjectFactory.build(csvDocumentToUse.allRows[0]);
                System.assert(false);
            } catch (Exception exceptionToHanlde) {
                System.assertEquals(true, exceptionToHanlde.getMessage().containsIgnoreCase('[Grant Award Name, Recipient ID]'));
            }
            System.assertEquals(0, [SELECT COUNT() FROM Account WHERE Name = 'This is a new recepient!']);
            System.assertEquals(0, [SELECT COUNT() FROM Grant_Award__c]);
            System.assertEquals(0, [SELECT COUNT() FROM Intermediary__c]);
        }
    }

    @isTest
    static void testInvalidInsertGrantAwardInvalidCCOAId() {
        initData();
        TestDataFactory testFactory = new TestDataFactory();
        User testSuperUser = testFactory.setupBasicUser(testDepartment, 'Super User 1', Constant.PROFILE_COMMUNITY_SUPER_USER);
        System.runAs(testSuperUser) {
            TestDataFactory.DEFAULT_GRANT_AWARD_DATA_PARSED.put(TestDataFactory.TEST_CCOA_COLUMN, 'Invalid CCOA Code');
            List<List<String>> allGrantAwardData = testFactory.createDefaultGrantAwardDataParsedCSV();
            CSVUploadSObjectFactory sobjectFactory = new CSVUploadSObjectFactory.CreateAwardsFactory();
            sobjectFactory.setCSVMapping(grantAwardMapping);
            CSVDocument csvDocumentToUse = new CSVDocument(allGrantAwardData);
            System.assertEquals(0, [SELECT COUNT() FROM Account WHERE Name = 'This is a new recepient!']);
            System.assertEquals(0, [SELECT COUNT() FROM Grant_Award__c]);
            System.assertEquals(0, [SELECT COUNT() FROM Intermediary__c]);
            try {
                sobjectFactory.build(csvDocumentToUse.allRows[0]);
                System.assert(false);
            } catch (CSVUploadSObjectFactory.NoRecordFoundException exceptionToHanlde) {
                System.assertEquals('No ' + TestDataFactory.TEST_CCOA_COLUMN + ' was found with the provided Id.', exceptionToHanlde.getMessage());
            }
            System.assertEquals(0, [SELECT COUNT() FROM Account WHERE Name = 'This is a new recepient!']);
            System.assertEquals(0, [SELECT COUNT() FROM Grant_Award__c]);
            System.assertEquals(0, [SELECT COUNT() FROM Intermediary__c]);
        }
    }

    @isTest
    static void testInvalidInsertGrantAwardBadCountryName() {
        initData();
        TestDataFactory testFactory = new TestDataFactory();
        User testSuperUser = testFactory.setupBasicUser(testDepartment, 'Super User 1', Constant.PROFILE_COMMUNITY_SUPER_USER);
        System.runAs(testSuperUser) {

            TestDataFactory.DEFAULT_GRANT_AWARD_DATA_PARSED.put(TestDataFactory.TEST_GRANT_AWARD_COUNTRY_COLUMN, 'Invalid Country Name');
            List<List<String>> allGrantAwardData = testFactory.createDefaultGrantAwardDataParsedCSV();

            CSVUploadSObjectFactory sobjectFactory = new CSVUploadSObjectFactory.CreateAwardsFactory();
            sobjectFactory.setCSVMapping(grantAwardMapping);
            CSVDocument csvDocumentToUse = new CSVDocument(allGrantAwardData);
            System.assertEquals(0, [SELECT COUNT() FROM Account WHERE Name = 'This is a new recepient!']);
            System.assertEquals(0, [SELECT COUNT() FROM Grant_Award__c]);
            System.assertEquals(0, [SELECT COUNT() FROM Intermediary__c]);
            try {
                sobjectFactory.build(csvDocumentToUse.allRows[0]);
                System.assert(false); // Ensures that this line never executes
            } catch (StringValueParser.InvalidInputException exceptionToHanlde) {
                System.assertEquals('Award Country contains an invalid value.', exceptionToHanlde.getMessage());
            }
            List<Grant_Award__c> insertedGrantAwards = [SELECT Recipient_Secondary_Country__c FROM Grant_Award__c];
            System.assertEquals(0, [SELECT COUNT() FROM Account WHERE Name = 'This is a new recepient!']);
            System.assertEquals(0, [SELECT COUNT() FROM Grant_Award__c]);
            System.assertEquals(0, [SELECT COUNT() FROM Intermediary__c]);
        }
    }

    @isTest
    static void testUpdateGrantAwardSuccess() {
        /**
        testCreateNewGrantAwardFull();

        TestDataFactory testFactory = new TestDataFactory();
        List<Grant_Award__c> insertedGrantAwards = [SELECT Grant_Award_Name__c FROM Grant_Award__c];
        System.assertEquals(1, insertedGrantAwards.size());
        System.assertEquals(TestDataFactory.TEST_GRANT_AWARD_NAME, insertedGrantAwards[0].Grant_Award_Name__c);
        System.assertEquals(1, [SELECT COUNT() FROM Account WHERE Name = 'This is a new recepient!']);
        System.assertEquals(2, [SELECT COUNT() FROM Intermediary__c]);

        User testSuperUser = testFactory.setupBasicUser(testDepartment, 'Super User 2', Constant.PROFILE_COMMUNITY_SUPER_USER);
        TestDataFactory.DEFAULT_GRANT_AWARD_DATA_PARSED.put(TestDataFactory.TEST_GRANT_AWARD_NAME_COLUMN, 'Updated Name for Grant Award!');
        List<List<String>> allGrantAwardData = testFactory.createDefaultGrantAwardDataParsedCSV();

        CSVUploadSObjectFactory sobjectFactory = new CSVUploadSObjectFactory.AmendAwardsFactory();

        CSV_Upload__c updateGrantAwardCsvUpload = testFactory.createOrganisationGrantAwardCSVUpload(Constant.CSV_UPLOAD_AMEND_AWARD_TYPE);
        grantAwardMapping = new CSVUploadMapping(updateGrantAwardCsvUpload);
        sobjectFactory.setCSVMapping(grantAwardMapping);

        CSVDocument csvDocumentToUse = new CSVDocument(allGrantAwardData);
        sobjectFactory.build(csvDocumentToUse.allRows[0]);
        List<Grant_Award__c> updatedGrantAwards = [SELECT Grant_Award_Name__c FROM Grant_Award__c];
        System.assertEquals(1, [SELECT COUNT() FROM Grant_Award__c]);
        System.assertEquals('Updated Name for Grant Award!', [SELECT Grant_Award_Name__c FROM Grant_Award__c LIMIT 1].Grant_Award_Name__c);
        System.assertEquals(1, [SELECT COUNT() FROM Account WHERE Name = 'This is a new recepient!']);
        System.assertEquals(2, [SELECT COUNT() FROM Intermediary__c]);
        **/
    }
    @isTest
    static void testUpdateGrantAwardFail() {
        /**
        testCreateNewGrantAwardFull();

        TestDataFactory testFactory = new TestDataFactory();
        List<Grant_Award__c> insertedGrantAwards = [SELECT Grant_Award_Name__c FROM Grant_Award__c];
        System.assertEquals(1, insertedGrantAwards.size());
        System.assertEquals(TestDataFactory.TEST_GRANT_AWARD_NAME, insertedGrantAwards[0].Grant_Award_Name__c);
        System.assertEquals(1, [SELECT COUNT() FROM Account WHERE Name = 'This is a new recepient!']);
        System.assertEquals(2, [SELECT COUNT() FROM Intermediary__c]);


        User testSuperUser = testFactory.setupBasicUser(testDepartment, 'Super User 2', Constant.PROFILE_COMMUNITY_SUPER_USER);

        TestDataFactory.DEFAULT_GRANT_AWARD_DATA_PARSED.put(TestDataFactory.TEST_GRANT_AWARD_REF_COLUMN, 'INVALID AWARD ID');
        List<List<String>> allGrantAwardData = testFactory.createDefaultGrantAwardDataParsedCSV();
        CSVUploadSObjectFactory sobjectFactory = new CSVUploadSObjectFactory.AmendAwardsFactory();

        CSV_Upload__c updateGrantAwardCsvUpload = testFactory.createOrganisationGrantAwardCSVUpload(Constant.CSV_UPLOAD_AMEND_AWARD_TYPE);
        grantAwardMapping = new CSVUploadMapping(updateGrantAwardCsvUpload);
        sobjectFactory.setCSVMapping(grantAwardMapping);

        CSVDocument csvDocumentToUse = new CSVDocument(allGrantAwardData);
        try {
            sobjectFactory.build(csvDocumentToUse.allRows[0]);
            System.assert(false, 'This line should never execute');
        } catch (CSVUploadSObjectFactory.NoRecordFoundException notFoundRecordExceptionToHandle) {
            //GEPDS-801 - 06 Apr 2016 - Showing different error message based on the checks
            System.assertEquals(notFoundRecordExceptionToHandle.getMessage(),
                                Label.Invalid_Grant_Ref_Num_Error);
        }
        List<Grant_Award__c> updatedGrantAwards = [SELECT Grant_Award_Name__c FROM Grant_Award__c];
        System.assertEquals(1, [SELECT COUNT() FROM Grant_Award__c]);
        System.assertEquals(TestDataFactory.TEST_GRANT_AWARD_NAME, [SELECT Grant_Award_Name__c FROM Grant_Award__c LIMIT 1].Grant_Award_Name__c);
        System.assertEquals(1, [SELECT COUNT() FROM Account WHERE Name = 'This is a new recepient!']);
        System.assertEquals(2, [SELECT COUNT() FROM Intermediary__c]);
        **/
    }

}