src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Is_My_Department_Data__c</fullName>
        <description>The user needs to have a default list view filtered for their own department, but they can change this</description>
        <formula>LEFT(
 Owner.UserRole.Name, 
 IF(
  RIGHT(Owner.UserRole.Name, 8) == &apos; Manager&apos;
  , LEN(Owner.UserRole.Name) - 8
  , LEN(Owner.UserRole.Name) - 5
 )
) == LEFT(
 $UserRole.Name, 
 IF(
  RIGHT($UserRole.Name, 8) == &apos; Manager&apos;
  , LEN($UserRole.Name) - 8
  , LEN($UserRole.Name) - 5
 )
)</formula>
        <label>Is My Department Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Address_1__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The first line of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_2__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The second line of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_City__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The city of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Country__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The country of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abu Dhabi</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Ajman</fullName>
                </value>
                <value>
                    <fullName>Akrotiri</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Ascension</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Baker Island</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_County__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The county of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Postal_Code__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The Location based data report is based on the accuracy of this postcode. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recipient</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Grant_Award__c.object
<CustomObject>
    <fields>
        <fullName>Get_existing_organisation_address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field indicated if the Grant Address should be copied over from the Recipient Address</description>
        <inlineHelpText>Check this box to use the recipient (organisation) address&apos;s details that already exist on the system. Leave this unchecked if you want to record, for this Grant Award, a different address from the one that the Recipient already has in the system.</inlineHelpText>
        <label>Get existing organisation address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_My_Department_Data__c</fullName>
        <description>The user needs to have a default list view filtered for their own department, but they can change this</description>
        <formula>LEFT(
 Grant_Scheme__r.Owner:User.UserRole.Name , 
 IF(
  RIGHT(Grant_Scheme__r.Owner:User.UserRole.Name, 8) == &apos; Manager&apos;
  , LEN(Grant_Scheme__r.Owner:User.UserRole.Name) - 8
  , LEN(Grant_Scheme__r.Owner:User.UserRole.Name) - 5
 )
)== LEFT(
 $UserRole.Name, 
 IF(
  RIGHT($UserRole.Name, 8) == &apos; Manager&apos;
  , LEN($UserRole.Name) - 8
  , LEN($UserRole.Name) - 5
 )
)</formula>
        <label>Is My Department Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recipient_Secondary_Address_1__c</fullName>
        <inlineHelpText>If a grant award is going to a different address than the one already stored for the Recipient Organisation, then populate the first line of the organisation&apos;s address.</inlineHelpText>
        <label>Recipient Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Secondary_Address_2__c</fullName>
        <inlineHelpText>If a grant award is going to a different address than the one already stored for the Recipient Organisation, then populate the second line of the organisation&apos;s address.</inlineHelpText>
        <label>Recipient Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Secondary_City__c</fullName>
        <inlineHelpText>If a grant award is going to a different address than the one already stored for the Recipient Organisation, then populate the city of the organisation&apos;s address.</inlineHelpText>
        <label>Recipient City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Secondary_Country__c</fullName>
        <inlineHelpText>If a grant award is going to a different address than the one alreday stored for the Recipient Organisation, then populate the country of the organisation&apos;s address.</inlineHelpText>
        <label>Recipient Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abu Dhabi</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Ajman</fullName>
                </value>
                <value>
                    <fullName>Akrotiri</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Ascension</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Baker Island</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recipient_Secondary_County__c</fullName>
        <inlineHelpText>If a grant award is going to a different address than the one already stored for the Recipient Organisation, then populate the county of the organisation&apos;s address.</inlineHelpText>
        <label>Recipient County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient_Secondary_Postal_Code__c</fullName>
        <inlineHelpText>The Location based data report is based on the accuracy of this postcode. If a grant award is going to a different address than the one already stored for the Recipient Organisation, then populate the postcode of the organisation&apos;s address.</inlineHelpText>
        <label>Recipient Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the grant recipient.</description>
        <inlineHelpText>For Recipient Type: Organisation. Name of the organisation that receives the grant.</inlineHelpText>
        <label>Recipient Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Grant Awards (Recipient)</relationshipLabel>
        <relationshipName>Grant_Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grant Award</label>
    <nameField>
        <displayFormat>GA-{000000}</displayFormat>
        <label>System Award Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AllGrantAwardTriggersHandler.cls
/******************************************************************************************
@Author         Divino Brinas
@Date           09/24/2015
@Project        Cloud Sherpas Cabinet Office Data Source
@Description    Main entry for all the trigger events on Grant_Award__c object
*******************************************************************************************/
public without sharing class AllGrantAwardTriggersHandler {

    private static final Set<String> AWARD_ADDRESS_FIELDS = new Set<String> {
        'Recipient_Secondary_Address_1__c',
        'Recipient_Secondary_Address_2__c',
        'Recipient_Secondary_City__c',
        'Recipient_Secondary_Country__c',
        'Recipient_Secondary_County__c',
        'Recipient_Secondary_Postal_Code__c'
    };

    public static void handleBeforeInsert(List<Grant_Award__c> newList) {
        List<Grant_Award__c> grantAwardToAddRecipientAddressTo = new List<Grant_Award__c>();
        for (Grant_Award__c grantAwardToCheck : newList) {
            Boolean hasRecipient = String.isNotBlank(grantAwardToCheck.Recipient__c);
            if (hasRecipient && grantAwardToCheck.Get_existing_organisation_address__c) {
                grantAwardToAddRecipientAddressTo.add(grantAwardToCheck);
            }
        }
        if (!grantAwardToAddRecipientAddressTo.isEmpty()) {
            addRecipientAddToGrantAward(grantAwardToAddRecipientAddressTo);
        }

        clearReasonForNoMonitoring(newlist);
        GrantFYcal.GrantFinancialYear(newList);
    }

    public static void handleBeforeUpdate(List<Grant_Award__c> newList, Map<Id, Grant_Award__c> oldGrantAwards) {
        List<Grant_Award__c> grantAwardToAddRecipientAddressTo = new List<Grant_Award__c>();
        for (Grant_Award__c updateGrantAwardToCheck : newList) {
            Grant_Award__c oldGrantAward = oldGrantAwards.get(updateGrantAwardToCheck.Id);
            Boolean getFromExistingOrganisationHasChange = oldGrantAward.Get_existing_organisation_address__c != updateGrantAwardToCheck.Get_existing_organisation_address__c;
            Boolean hasAnyAddressValueChanged = getHasAnyAddressValueChanged(oldGrantAward, updateGrantAwardToCheck);
            Boolean hasRecipient = String.isNotBlank(updateGrantAwardToCheck.Recipient__c);
            if (getFromExistingOrganisationHasChange && hasRecipient && updateGrantAwardToCheck.Get_existing_organisation_address__c) {
                grantAwardToAddRecipientAddressTo.add(updateGrantAwardToCheck);
            } else if (hasAnyAddressValueChanged) {
                updateGrantAwardToCheck.Get_existing_organisation_address__c = false;
            }
        }
        if (!grantAwardToAddRecipientAddressTo.isEmpty()) {
            addRecipientAddToGrantAward(grantAwardToAddRecipientAddressTo);
        }

        clearReasonForNoMonitoring(newlist);
        GrantFYcal.GrantFinancialYear(newList);
    }

    private static Boolean getHasAnyAddressValueChanged(Grant_Award__c oldGrantAward, Grant_Award__c updateGrantAwardToCheck) {
        for (String addressFieldtoCheck : AWARD_ADDRESS_FIELDS) {
            String oldValue = (String) oldGrantAward.get(addressFieldtoCheck);
            String newValue = (String) updateGrantAwardToCheck.get(addressFieldtoCheck);
            if (oldValue != newValue) {
                return true;
            }
        }
        return false;
    }

    private static void addRecipientAddToGrantAward(List<Grant_Award__c> awardsToChange) {
        Set<Id> recipientIds = new Set<Id>();
        for (Grant_Award__c awardToChange : awardsToChange) {
            recipientIds.add(awardToChange.Recipient__c);
        }
        Map<Id, Account> queriedRecipients = new Map<Id, Account>([
                    SELECT Id, Primary_Address_1__c, Primary_Address_2__c, Primary_City__c,
                    Primary_County__c, Primary_Postal_Code__c, Primary_Country__c
                    FROM Account
                    WHERE Id IN :recipientIds
                ]);
        for (Grant_Award__c awardToChange : awardsToChange) {
            Account recipientToUse = queriedRecipients.get(awardToChange.Recipient__c);
            awardToChange.Recipient_Secondary_Address_1__c = recipientToUse.Primary_Address_1__c;
            awardToChange.Recipient_Secondary_Address_2__c = recipientToUse.Primary_Address_2__c;
            awardToChange.Recipient_Secondary_City__c = recipientToUse.Primary_City__c;
            awardToChange.Recipient_Secondary_Country__c = recipientToUse.Primary_Country__c;
            awardToChange.Recipient_Secondary_County__c = recipientToUse.Primary_County__c;
            awardToChange.Recipient_Secondary_Postal_Code__c = recipientToUse.Primary_Postal_Code__c;
        }
    }

    public static void handleBeforeDelete(Map<Id, Grant_Award__c> oldMap) {
        User u = [SELECT Profile.NAME FROM User WHERE ID = :UserInfo.getUserID()]; 
        If(u.profile.NAME != 'System Administrator'){
            Map<Id, Grant_Award__c> queriedGrantAwards = new Map<Id, Grant_Award__c>([
                        SELECT Id, Is_My_Department_Data__c, Portal_User_Cannot_Delete_This_Record__c
                        FROM Grant_Award__c
                        WHERE Id IN :oldMap.keySet()
                    ]);
            for (Grant_Award__c grantAwardToCheck : oldMap.values()) {
                Grant_Award__c queriedGrantAward = queriedGrantAwards.get(grantAwardToCheck.id);
                checkUserDepartment(queriedGrantAward, grantAwardToCheck);
                if (queriedGrantAward.Portal_User_Cannot_Delete_This_Record__c) {
                    grantAwardToCheck.addError(System.Label.Grant_Award_Delete_Validation_Error_Message);
                }
            }
        }
    }
    private static void checkUserDepartment(Grant_Award__c queriedGrantAward, Grant_Award__c grantAwardToCheck) {
        Boolean isRunningUserRoleDifferentFromOwnerUserRole = /** UserInfo.getUserType() == Constant.USER_TYPE_COMMUNITY_PLUS**/!queriedGrantAward.Is_My_Department_Data__c;
        if (isRunningUserRoleDifferentFromOwnerUserRole) {
            grantAwardToCheck.addError(System.Label.User_Delete_Access_Error_Msg);
        }
    }

    /**
     * method to clear the 'Reason for no mentoring' field when is the Grant is monitored
     * @author  Bhushan Sukumar
     * @date    29 Mar 2016
     * @param   newList  trigger list
     */
    private static void clearReasonForNoMonitoring(List<Grant_Award__c> newList) {
        for (Grant_Award__c award : newlist) {
            try {
                if (award.Is_The_Grant_Monitored__c == Constant.GRANT_MONITORED_YES &&
                        !String.isBlank(award.Reason_For_No_Monitoring__c)) {
                    award.Reason_For_No_Monitoring__c = '';
                }
            } catch (Exception e) {
                award.addError(Label.Grant_Award_Update_Exception_Msg + award.Grant_Scheme__c);
                award.addError(e.getMessage());
            }
        }
    }
}