src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CPID_from_OSCAR__c</fullName>
        <description>This is an external id that will be used for the data upload process.</description>
        <externalId>true</externalId>
        <inlineHelpText>Counter-Party Identifier Code (CPID). The Treasury produced a list of all bodies within the Whole of Government Accounts boundary (WGA). Each WGA body is issued by the Treasury with a unique CPID code. To be provided if applicable.</inlineHelpText>
        <label>CPID (from OSCAR)</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Intermediary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Intermediary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VAT_Reg_no__c</fullName>
        <description>This is an external id that will be used for the data upload process.</description>
        <externalId>true</externalId>
        <inlineHelpText>Tax registration number. To be provided if applicable.</inlineHelpText>
        <label>VAT Reg no</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/COFOG_L2__c.object
<CustomObject>
    <fields>
        <fullName>COFOG_L2_Long_Name__c</fullName>
        <label>COFOG L2 Long Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>COFOG L2</label>
    <nameField>
        <label>COFOG L2 Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>COFOG L2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CSV_Upload__c.object
<CustomObject>
    <description>This is the object that saves the CSV upload attempts by super users.</description>
    <fields>
        <fullName>Apex_Batch_Id__c</fullName>
        <description>This is the Salesforce ID for the corresponding batch job for this upload attempt.</description>
        <externalId>true</externalId>
        <label>Apex Batch Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <description>This is the batch status for this CSV upload item.</description>
        <label>Processing Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Finished</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Records_Created_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total number of records inserted in by this csv upload process.</description>
        <inlineHelpText>Total number of records inserted in by this csv upload process.</inlineHelpText>
        <label>Records Created Count</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Records_Updated_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total number of records updated in by this csv upload process.</description>
        <inlineHelpText>Total number of records updated in by this csv upload process.</inlineHelpText>
        <label>Records Updated Count</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Records_Failed__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the total number of records failed the upload process.</description>
        <label>Total Records Failed</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Records_To_Be_Processed__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total number of records processed for this CSV upload</description>
        <label>Total Records To Be Processed</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Data Upload</label>
    <nameField>
        <displayFormat>CSVU-{0000000}</displayFormat>
        <label>FileUpload Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Uploads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Grant_Award__c.object
<CustomObject>
    <fields>
        <fullName>Grant_Scheme__c</fullName>
        <description>This is the parent scheme for this award</description>
        <inlineHelpText>This is the System Scheme Reference No and clicking it will take you back to the Scheme that this award belong to.</inlineHelpText>
        <label>Grant Scheme</label>
        <referenceTo>Grant_Scheme__c</referenceTo>
        <relationshipLabel>Grant Awards</relationshipLabel>
        <relationshipName>Grant_Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Grant Award</label>
    <nameField>
        <displayFormat>GA-{000000}</displayFormat>
        <label>System Award Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Grant_Scheme__c.object
<CustomObject>
    <fields>
        <fullName>COFOG_L2__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the related COFOG L2 Code for this Scheme.</description>
        <inlineHelpText>Classification of the Functions of Government - values, levels 1 and 2, are taken from the United Nations Statistics Division classification published at unstats.un.org</inlineHelpText>
        <label>COFOG L2</label>
        <referenceTo>COFOG_L2__c</referenceTo>
        <relationshipLabel>Grant Schemes</relationshipLabel>
        <relationshipName>Grant_Schemes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scheme_Reference_No__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is a reference number that can be given from a department&apos;s own internal system, should you wish to. It is optional &amp; will help reconciliation between GGIS &amp; your own system, but you don&apos;t have to include one.</inlineHelpText>
        <label>Scheme Reference No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Grant Scheme</label>
    <nameField>
        <displayFormat>SCH-{000000000}</displayFormat>
        <label>System Scheme Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Intermediary__c.object
<CustomObject>
    <description>This is the organisation which carries out the intermediary role</description>
    <fields>
        <fullName>Grant_Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the related grant award for this intermediary record</description>
        <label>System Award Reference No</label>
        <referenceTo>Grant_Award__c</referenceTo>
        <relationshipLabel>Intermediaries</relationshipLabel>
        <relationshipName>Intermediaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant_Scheme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the related grant scheme</description>
        <label>System Scheme Reference No</label>
        <referenceTo>Grant_Scheme__c</referenceTo>
        <relationshipLabel>Intermediaries</relationshipLabel>
        <relationshipName>Intermediaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intermediary_Organisation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Related organisation for this intermediary</description>
        <inlineHelpText>Organisations who distribute or administer grants on behalf of a government department i.e. a government agency, NDPB, charity or business. In some cases, a government department can act as an intermediary for another government department.</inlineHelpText>
        <label>Intermediary Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Intermediaries</relationshipLabel>
        <relationshipName>Intermediaries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>The intermediary role carried out by the organisation</description>
        <inlineHelpText>The role that an intermediary plays in the grant administration process. You can choose multiple roles.</inlineHelpText>
        <label>Role</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Market Engagement Advertising</fullName>
                </value>
                <value>
                    <fullName>Application Assessment</fullName>
                </value>
                <value>
                    <fullName>Due Diligence</fullName>
                </value>
                <value>
                    <fullName>Grant Award</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Performance Monitoring</fullName>
                </value>
                <value>
                    <fullName>Final Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Evaluation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Intermediary</label>
    <nameField>
        <displayFormat>INT-{00000000}</displayFormat>
        <label>Intermediary Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intermediaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CSVUploadProcessorTest.cls
/******************************************************************************************
@Author         Hamed Izadpanah
@Date           03/10/2015
@Project        Cloud Sherpas Cabinet Office Data Source
@Description    This is the unit test for CSV Upload Processor batch class
*******************************************************************************************/
@isTest
private class CSVUploadProcessorTest {

	@testSetup()
	private static void setupTestData(){
		
		insert new CoA_L5__c(
			Name = TestDataFactory.TEST_CCOA_CODE
		);
		TestDataFactory testFactory = new TestDataFactory();
		insert testFactory.createDefaultCSVColumnMappingItems();
		COFOG_L2__c newCOFOG = new COFOG_L2__c(
			Name = '123',
			COFOG_L2_Long_Name__c = 'RT'
		);
		insert newCOFOG;
		Account funderAccount = testFactory.createAccount('New Funder', 'FUN123');
		Account testDepartment = testFactory.createAccount('My New Department', 'DEP123');
		insert new List<Account>{funderAccount, testDepartment};
		User testSuperUser = testFactory.setupBasicUser(testDepartment, 'Super User 0', Constant.PROFILE_COMMUNITY_SUPER_USER);
		System.runAs(testSuperUser){
			Grant_Scheme__c newGrantScheme = testFactory.createGrantScheme(funderAccount, 'New Scheme', newCOFOG);
			newGrantScheme.Scheme_Reference_No__c = 'MySchemeRefNumber';
			insert newGrantScheme;
		}
	}

	static Account testDepartment;
	static void initData(){
		testDepartment = [SELECT Id FROM Account WHERE CPID_from_OSCAR__c = 'DEP123' LIMIT 1][0];
	}


	@isTest
	static void testCreateNewGrantAwardFull(){
		initData();
		TestDataFactory testFactory = new TestDataFactory();
		User testSuperUser = testFactory.setupBasicUser(testDepartment, 'Super User 1', Constant.PROFILE_COMMUNITY_SUPER_USER);
		System.runAs(testSuperUser){
			List<List<String>> allGrantAwardData = testFactory.createDefaultGrantAwardDataParsedCSV();
			System.assertEquals(0, [SELECT COUNT() FROM Grant_Award__c]);
			System.assertEquals(0, [SELECT COUNT() FROM Account WHERE Name = 'This is a new recepient!']);
			System.assertEquals(0, [SELECT COUNT() FROM Intermediary__c]);
			System.assertEquals(0, [SELECT COUNT() FROM CSV_Upload__c]);
			CSVDocument documentToUpload = new CSVDocument(allGrantAwardData);
			CSV_Upload__c csvUpload = testFactory.createOrganisationGrantAwardCSVUpload(Constant.CSV_UPLOAD_CREATE_AWARD_TYPE);
			CSVUploadProcessor processor = new CSVUploadProcessor(documentToUpload, CSVUploadSObjectFactory.newInstance(csvUpload));
			Test.startTest();
				Database.executeBatch(processor, 1);
			Test.stopTest();
			List<CSV_Upload__c> createdCSVUpload = [SELECT Records_Created_Count__c, Records_Updated_Count__c, Processing_Status__c, Total_Records_Failed__c FROM CSV_Upload__c];
			System.assertEquals(1, createdCSVUpload.size());
			System.assertEquals(Constant.CSV_UPLOAD_PT_FINISHED, createdCSVUpload[0].Processing_Status__c);
			System.assertEquals(1, createdCSVUpload[0].Records_Created_Count__c);
			System.assertEquals(0, createdCSVUpload[0].Records_Updated_Count__c);
			System.assertEquals(0, createdCSVUpload[0].Total_Records_Failed__c);

			System.assertEquals(1, [SELECT COUNT() FROM Account WHERE Name = 'This is a new recepient!']);
			System.assertEquals(1, [SELECT COUNT() FROM Grant_Award__c]);
			System.assertEquals(1, [
				SELECT COUNT() 
				FROM Intermediary__c 
				WHERE Intermediary_Organisation__r.Name = :TestDataFactory.NEW_INTERMEDIARY_1_NAME 
				AND Role__c = :TestDataFactory.NEW_INTERMEDIARY_1_ROLE 
				AND Intermediary_Organisation__r.VAT_Reg_no__c = :TestDataFactory.NEW_INTERMEDIARY_1_ORGANISATION_ID
			]);
			System.assertEquals(1, [
				SELECT COUNT() 
				FROM Intermediary__c 
				WHERE Intermediary_Organisation__r.Name = :TestDataFactory.NEW_INTERMEDIARY_2_NAME
				AND Role__c = :TestDataFactory.NEW_INTERMEDIARY_2_ROLE 
				AND Intermediary_Organisation__r.VAT_Reg_no__c = :TestDataFactory.NEW_INTERMEDIARY_2_ORGANISATION_ID
			]);
		}
	}

	@isTest
	static void testInvalidInsertGrantAwardNoNameAndRecepientId(){
		initData();
		TestDataFactory testFactory = new TestDataFactory();
		User testSuperUser = testFactory.setupBasicUser(testDepartment, 'Super User 1', Constant.PROFILE_COMMUNITY_SUPER_USER);
		System.runAs(testSuperUser){
		
			TestDataFactory.DEFAULT_GRANT_AWARD_DATA_PARSED.put(TestDataFactory.TEST_GRANT_AWARD_NAME_COLUMN, '');
			TestDataFactory.DEFAULT_GRANT_AWARD_DATA_PARSED.put(TestDataFactory.TEST_RECEPIENT_ID_COLUMN, '');
			List<List<String>> allGrantAwardData = testFactory.createDefaultGrantAwardDataParsedCSV();

			System.assertEquals(0, [SELECT COUNT() FROM Account WHERE Name = 'This is a new recepient!']);
			System.assertEquals(0, [SELECT COUNT() FROM Grant_Award__c]);
			System.assertEquals(0, [SELECT COUNT() FROM Intermediary__c]);

			CSVDocument documentToUpload = new CSVDocument(allGrantAwardData);
			CSV_Upload__c csvUpload = testFactory.createOrganisationGrantAwardCSVUpload(Constant.CSV_UPLOAD_CREATE_AWARD_TYPE);
			CSVUploadProcessor processor = new CSVUploadProcessor(documentToUpload, CSVUploadSObjectFactory.newInstance(csvUpload));
			System.assertEquals(0, [SELECT COUNT() FROM CSV_Upload__c]);
			Test.startTest();
				CSV_Upload__c newUpload = testFactory.createOrganisationGrantAwardCSVUpload(Constant.CSV_UPLOAD_CREATE_AWARD_TYPE);
				newUpload.Total_Records_Failed__c = 0;
				newUpload.Total_Records_To_Be_Processed__c = 1;
				newUpload.Apex_Batch_Id__c = Id.valueOf(Database.executeBatch(processor, 1));
				newUpload.Processing_Status__c = Constant.CSV_UPLOAD_PT_QUEUED;
				insert newUpload;
				System.assertEquals(0, [SELECT COUNT() FROM Attachment WHERE ParentId = :newUpload.Id]);
			Test.stopTest();

			List<CSV_Upload__c> createdCSVUpload = [SELECT Records_Created_Count__c, Records_Updated_Count__c, Processing_Status__c, Total_Records_Failed__c FROM CSV_Upload__c];
			System.assertEquals(1, createdCSVUpload.size());
			System.assertEquals(Constant.CSV_UPLOAD_PT_FINISHED, createdCSVUpload[0].Processing_Status__c);
			System.assertEquals(0, createdCSVUpload[0].Records_Created_Count__c);
			System.assertEquals(0, createdCSVUpload[0].Records_Updated_Count__c);
			System.assertEquals(1, createdCSVUpload[0].Total_Records_Failed__c);

			List<Attachment> errorFiles = [SELECT Body FROM Attachment WHERE ParentId = :newUpload.Id];
			System.assertEquals(1, errorFiles.size());
			System.assertEquals(true, errorFiles[0].Body.toString().containsIgnoreCase('[Grant Award Name, Recipient ID]'));
			System.assertEquals(0, [SELECT COUNT() FROM Account WHERE Name = 'This is a new recepient!']);
			System.assertEquals(0, [SELECT COUNT() FROM Grant_Award__c]);
			System.assertEquals(0, [SELECT COUNT() FROM Intermediary__c]);
		}
	}

	@isTest
	static void testInvalidInsertGrantAwardWithoutCountry(){
		initData();
		TestDataFactory testFactory = new TestDataFactory();
		User testSuperUser = testFactory.setupBasicUser(testDepartment, 'Super User 1', Constant.PROFILE_COMMUNITY_SUPER_USER);
		System.runAs(testSuperUser){
			String longName = '';
			while(longName.length() < 255){
				longName += 'LONG NAME!!!';
			}
			TestDataFactory.DEFAULT_GRANT_AWARD_DATA_PARSED.put(TestDataFactory.TEST_GRANT_AWARD_NAME_COLUMN, longName);
			List<List<String>> allGrantAwardData = testFactory.createDefaultGrantAwardDataParsedCSV();
			System.assertEquals(0, [SELECT COUNT() FROM Account WHERE Name = 'This is a new recepient!']);
			System.assertEquals(0, [SELECT COUNT() FROM Grant_Award__c]);
			System.assertEquals(0, [SELECT COUNT() FROM Intermediary__c]);
			CSVDocument documentToUpload = new CSVDocument(allGrantAwardData);
			CSV_Upload__c csvUpload = testFactory.createOrganisationGrantAwardCSVUpload(Constant.CSV_UPLOAD_CREATE_AWARD_TYPE);
			CSVUploadProcessor processor = new CSVUploadProcessor(documentToUpload, CSVUploadSObjectFactory.newInstance(csvUpload));
			Test.startTest();
				CSV_Upload__c newUpload = testFactory.createOrganisationGrantAwardCSVUpload(Constant.CSV_UPLOAD_CREATE_AWARD_TYPE);
				newUpload.Total_Records_Failed__c = 0;
				newUpload.Total_Records_To_Be_Processed__c = 1;
				newUpload.Apex_Batch_Id__c = Id.valueOf(Database.executeBatch(processor, 1));
				newUpload.Processing_Status__c = Constant.CSV_UPLOAD_PT_QUEUED;
				insert newUpload;
				System.assertEquals(0, [SELECT COUNT() FROM Attachment WHERE ParentId = :newUpload.Id]);
			Test.stopTest();
			List<Attachment> errorFiles = [SELECT Body FROM Attachment WHERE ParentId = :newUpload.Id];
			System.assertEquals(1, errorFiles.size());
			System.assertEquals(true, errorFiles[0].Body.toString().containsIgnoreCase('(max length=255)'));
			System.assertEquals(0, [SELECT COUNT() FROM Account WHERE Name = 'This is a new recepient!']);
			System.assertEquals(0, [SELECT COUNT() FROM Grant_Award__c]);
			System.assertEquals(0, [SELECT COUNT() FROM Intermediary__c]);
		}
	}

}