src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Funder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Funder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Intermediary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Intermediary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recipient</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Grant_Award__c.object
<CustomObject>
    <fields>
        <fullName>Grant_Scheme__c</fullName>
        <description>This is the parent scheme for this award</description>
        <inlineHelpText>This is the System Scheme Reference No and clicking it will take you back to the Scheme that this award belong to.</inlineHelpText>
        <label>Grant Scheme</label>
        <referenceTo>Grant_Scheme__c</referenceTo>
        <relationshipLabel>Grant Awards</relationshipLabel>
        <relationshipName>Grant_Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the grant recipient.</description>
        <inlineHelpText>For Recipient Type: Organisation. Name of the organisation that receives the grant.</inlineHelpText>
        <label>Recipient Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Grant Awards (Recipient)</relationshipLabel>
        <relationshipName>Grant_Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Grant Award</label>
    <nameField>
        <displayFormat>GA-{000000}</displayFormat>
        <label>System Award Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Grant_Scheme__c.object
<CustomObject>
    <fields>
        <fullName>Funder__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the funder organisation lookup</description>
        <inlineHelpText>The entity that is funding the grant scheme (this is in most cases, a government department where the funds start)</inlineHelpText>
        <label>Funder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Is_Funder__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Grant Schemes (Funder)</relationshipLabel>
        <relationshipName>Grant_Schemes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Grant Scheme</label>
    <nameField>
        <displayFormat>SCH-{000000000}</displayFormat>
        <label>System Scheme Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Intermediary__c.object
<CustomObject>
    <description>This is the organisation which carries out the intermediary role</description>
    <fields>
        <fullName>Grant_Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the related grant award for this intermediary record</description>
        <label>System Award Reference No</label>
        <referenceTo>Grant_Award__c</referenceTo>
        <relationshipLabel>Intermediaries</relationshipLabel>
        <relationshipName>Intermediaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant_Scheme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the related grant scheme</description>
        <label>System Scheme Reference No</label>
        <referenceTo>Grant_Scheme__c</referenceTo>
        <relationshipLabel>Intermediaries</relationshipLabel>
        <relationshipName>Intermediaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intermediary_Organisation__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Related organisation for this intermediary</description>
        <inlineHelpText>Organisations who distribute or administer grants on behalf of a government department i.e. a government agency, NDPB, charity or business. In some cases, a government department can act as an intermediary for another government department.</inlineHelpText>
        <label>Intermediary Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Intermediaries</relationshipLabel>
        <relationshipName>Intermediaries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Intermediary</label>
    <nameField>
        <displayFormat>INT-{00000000}</displayFormat>
        <label>Intermediary Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intermediaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CabinetOffice/src/classes/AllAccountTriggersHandler.cls
/******************************************************************************************
@Author         Hamed Izadpanah
@Date           28/09/2015
@Project        Cloud Sherpas Cabinet Office Data Source
@Description    Main entry for all the trigger events on Account object
*******************************************************************************************/
public without sharing class AllAccountTriggersHandler {

	public static void handleBeforeDelete(Map<Id, Account> oldMap){
		Map<Id, Account> queriedAccounts = new Map<Id, Account>([
			SELECT Id, Owner.UserRoleId
			FROM Account
			WHERE Id IN :oldMap.keySet()
		]);
		for(Account accountToCheck : oldMap.values()){
			Account queriedAccount = queriedAccounts.get(accountToCheck.Id);
			checkUserDepartment(queriedAccount, accountToCheck);
		}
		checkChildAccountRecords(oldMap);
		checkRelatedRecords(oldMap);
	}

	private static void checkChildAccountRecords(Map<Id, Account> oldMap) {
		Map<Id, AggregateResult> childAccountCountMap = new Map<Id, AggregateResult>([
			SELECT ParentId Id, COUNT(Id) childCount
			FROM Account 
			WHERE ParentId IN : oldMap.keySet()
			GROUP BY ParentId]);
		
		for (Account organisationToCheck : oldMap.values()) {
			Integer orgChildCount = childAccountCountMap.containsKey(organisationToCheck.Id) ? (Integer) childAccountCountMap.get(organisationToCheck.Id).get('childCount') : 0;

			if (orgChildCount > 0) {
				organisationToCheck.addError(System.Label.Organisation_Has_Child_Delete_Error_Message);
			}
		}

	}

	private static void checkRelatedRecords(Map<Id, Account> oldMap){
		Map<Id, AggregateResult> relatedSchemesCountMap = new Map<Id, AggregateResult>([
			SELECT Funder__c Id, COUNT(Id) schemesCount 
			FROM Grant_Scheme__C 
			WHERE Funder__c IN :oldMap.keySet() 
			GROUP BY Funder__c
		]);
		Map<Id, AggregateResult> relatedAwardsCountMap = new Map<Id, AggregateResult>([
			SELECT Recipient__c Id, COUNT(Id) awardsCount 
			FROM Grant_Award__C 
			WHERE Recipient__c IN :oldMap.keySet() 
			GROUP BY Recipient__c
		]);
		Map<Id, AggregateResult> relatedIntermediariesCountMap = new Map<Id, AggregateResult>([
			SELECT Intermediary_Organisation__c Id, COUNT(Id) intermediariesCount 
			FROM Intermediary__c 
			WHERE Intermediary_Organisation__c IN :oldMap.keySet() 
			GROUP BY Intermediary_Organisation__c
		]);
		for(Account organisationToCheck : oldMap.values()){
			Integer relatedSchemesCount = relatedSchemesCountMap.containsKey(organisationToCheck.Id) ? (Integer) relatedSchemesCountMap.get(organisationToCheck.Id).get('schemesCount') : 0;
			Integer relatedAwardsCount = relatedAwardsCountMap.containsKey(organisationToCheck.Id) ? (Integer) relatedAwardsCountMap.get(organisationToCheck.Id).get('awardsCount') : 0;
			Integer relatedIntermediariesCount = relatedIntermediariesCountMap.containsKey(organisationToCheck.Id) ? (Integer) relatedIntermediariesCountMap.get(organisationToCheck.Id).get('intermediariesCount') : 0;
			if(relatedSchemesCount > 0 || relatedAwardsCount > 0 || relatedIntermediariesCount > 0){
				organisationToCheck.addError(System.Label.Organisation_Related_Grants_Delete_Error_Message);
			}
		}
	}

	private static void checkUserDepartment(Account queriedAccount, Account accountToCheck){
		Boolean isRunningUserRoleDifferentFromOwnerUserRole = UserInfo.getUserType() == Constant.USER_TYPE_COMMUNITY_PLUS && UserInfo.getUserRoleId() != queriedAccount.Owner.UserRoleId;
		if(isRunningUserRoleDifferentFromOwnerUserRole){
			accountToCheck.addError(System.Label.User_Delete_Access_Error_Msg);
		}
	}
}