src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Address_1__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The first line of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_2__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The second line of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_City__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The city of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Country__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The country of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abu Dhabi</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Ajman</fullName>
                </value>
                <value>
                    <fullName>Akrotiri</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Ascension</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Baker Island</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>United Kingdom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_County__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The county of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Postal_Code__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The Location based data report is based on the accuracy of this postcode. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Grant_Award__c.object
<CustomObject>
    <fields>
        <fullName>Grant_Scheme__c</fullName>
        <description>This is the parent scheme for this award</description>
        <inlineHelpText>This is the System Scheme Reference No and clicking it will take you back to the Scheme that this award belong to.</inlineHelpText>
        <label>Grant Scheme</label>
        <referenceTo>Grant_Scheme__c</referenceTo>
        <relationshipLabel>Grant Awards</relationshipLabel>
        <relationshipName>Grant_Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Risk_Profile__c</fullName>
        <inlineHelpText>A explanation of this field can be found in our Glossary of Terms. This can be downloaded from the front page</inlineHelpText>
        <label>Risk Profile</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant Award</label>
    <nameField>
        <displayFormat>GA-{000000}</displayFormat>
        <label>System Award Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Grant_Scheme__c.object
<CustomObject>
    <fields>
        <fullName>Contact_email_address__c</fullName>
        <description>This is the email of the System administrator.</description>
        <inlineHelpText>This is the person in a department/ ALB in charge of administering the grant within government that will know more about the grant and can be contacted for further details, either by other departments or internally.</inlineHelpText>
        <label>Internal Grant Administrator email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>The Scheme&apos;s duration</description>
        <inlineHelpText>How long the scheme will run for. The duration is from the scheme opening to the last grants ending.</inlineHelpText>
        <label>Duration (years)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Public_funding_source__c</fullName>
        <description>the source of public funding</description>
        <inlineHelpText>The source of funding for the grant scheme. This could be from the UK Exchequer,  EU Funding, both, Lottery Funding, NATO or other type.</inlineHelpText>
        <label>Public funding source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>UK Exchequer</fullName>
                </value>
                <value>
                    <fullName>EU Funding</fullName>
                </value>
                <value>
                    <fullName>UK + EU funding</fullName>
                </value>
                <value>
                    <fullName>Lottery funding</fullName>
                </value>
                <value>
                    <fullName>NATO</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Risk_Profile__c</fullName>
        <inlineHelpText>A explanation of this field can be found in our Glossary of Terms. This can be downloaded from the front page</inlineHelpText>
        <label>Scheme risk profile</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scheme_Value__c</fullName>
        <inlineHelpText>The total value of the scheme (budgeted). If the scheme has a multiple year duration, the scheme value should include all years. If scheme value is not known for multiple years, please create 1 separate scheme per year, with 1 year scheme value only.</inlineHelpText>
        <label>Scheme Value</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Senior_Responsible_Officer_Full_Name__c</fullName>
        <label>Senior Responsible Officer - Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>The date the Grant Scheme commences</inlineHelpText>
        <label>Scheme start date</label>
        <type>Date</type>
    </fields>
    <label>Grant Scheme</label>
    <nameField>
        <displayFormat>SCH-{000000000}</displayFormat>
        <label>System Scheme Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GrantFYcalTest.cls
@isTest
private class GrantFYcalTest {
	private static testMethod void TestGrantFinancialYear(){
	    TestDataFactory testFactory = new TestDataFactory();
        testFactory.insertReferenceData();
        Account department1 = testFactory.createAccount('Department1','NEW_CPID_Department1');
        department1.Primary_Address_1__c = 'Unit 1, Horse Guards Rd';
        department1.Primary_Address_2__c = 'HM Treasury';
        department1.Primary_City__c = 'London';
        department1.Primary_County__c = 'Greater London';
        department1.Primary_Country__c = 'United Kingdom';
        department1.Primary_Postal_Code__c = 'SW1A 2HQ';
        insert department1;
        User dept1SuperUser1 = testFactory.setupBasicUser(department1 ,'SuperUserContact1','Data Solution Portal - Super User');
        insert dept1SuperUser1;
        System.runAs(dept1SuperUser1){
            Grant_Scheme__c grantSchemeCreatedByDept1SuperUser1 = testFactory.createGrantScheme(
              department1, 'Test Grant scheme NonAdminRecord01', testFactory.testCOFOGLevel);
	    grantSchemeCreatedByDept1SuperUser1.Start_Date__C = date.valueOf('2016-04-01');
	    grantSchemeCreatedByDept1SuperUser1.Duration__C = '5';
	    grantSchemeCreatedByDept1SuperUser1.Risk_Profile__c ='Medium';
	    grantSchemeCreatedByDept1SuperUser1.Senior_Responsible_Officer_Full_Name__c = 'test';
	    grantSchemeCreatedByDept1SuperUser1.Scheme_Value__c = 2234;
	    grantSchemeCreatedByDept1SuperUser1.Contact_email_address__c ='test@test.com';
	    grantSchemeCreatedByDept1SuperUser1.Public_funding_source__c ='NATO';
	    grantSchemeCreatedByDept1SuperUser1.Primary_Purpose__c ='Research & Innovation';
	    grantSchemeCreatedByDept1SuperUser1.Allocation_Method__c = 'Formula';
	    grantSchemeCreatedByDept1SuperUser1.Target_Location__c = 'England';
	    grantSchemeCreatedByDept1SuperUser1.Recipient_Sector__c = 'Central Government';
	    grantSchemeCreatedByDept1SuperUser1.Considered_by_the_Grants_Advice_Panel__c ='No';
	    grantSchemeCreatedByDept1SuperUser1.Capital_Resource__c ='Capital';
	    grantSchemeCreatedByDept1SuperUser1.Related_policy_objective__c ='test';
	    Database.Insert(grantSchemeCreatedByDept1SuperUser1);
	    
	    
	    Grant_Award__c grantAwardCreatedByDept1SuperUser1 = testFactory.createGrantAward('Test Grant Award NonAdminRecord01', department1,grantSchemeCreatedByDept1SuperUser1);
	    
	    Test.startTest();
	    Database.Insert(grantAwardCreatedByDept1SuperUser1);
	    Test.stopTest();
        }
	}

}