src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Address_1__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The first line of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_2__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The second line of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_City__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The city of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Country__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The country of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abu Dhabi</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Ajman</fullName>
                </value>
                <value>
                    <fullName>Akrotiri</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Ascension</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Baker Island</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>United Kingdom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_County__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The county of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Postal_Code__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The Location based data report is based on the accuracy of this postcode. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Grant_Award__c.object
<CustomObject>
    <fields>
        <fullName>Award_End_Date__c</fullName>
        <inlineHelpText>The date the grant closes, as per grant award agreement or letter.</inlineHelpText>
        <label>Award End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Award_Start_Date__c</fullName>
        <inlineHelpText>The date the grant was issued, as per grant award agreement or letter.</inlineHelpText>
        <label>Award Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grant_Scheme__c</fullName>
        <description>This is the parent scheme for this award</description>
        <inlineHelpText>This is the System Scheme Reference No and clicking it will take you back to the Scheme that this award belong to.</inlineHelpText>
        <label>Grant Scheme</label>
        <referenceTo>Grant_Scheme__c</referenceTo>
        <relationshipLabel>Grant Awards</relationshipLabel>
        <relationshipName>Grant_Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Has_Postal_Code_Been_Checked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates if the postcode has been validated or not</description>
        <label>Has Postal Code Been Checked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Postal_Code_Valid__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates if the value for this post code is valid or not.</description>
        <inlineHelpText>This checkbox indicates if the value for this post code is valid or not.</inlineHelpText>
        <label>Is Postal Code Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Parliamentary_Constituency__c</fullName>
        <description>This value is generated automated based on the selected postcode.</description>
        <label>Postal Code Parliamentary Constituency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Region__c</fullName>
        <description>This value is generated automatically based on the selected postal code.</description>
        <label>Postal Code Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Amount_in_funding_agreement__c</fullName>
        <inlineHelpText>For Recipient Type: Organisation. The total amount in pounds of the grant award that was comitted in the grant award agreement.</inlineHelpText>
        <label>Total Amount in funding agreement in GBP</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Grant Award</label>
    <nameField>
        <displayFormat>GA-{000000}</displayFormat>
        <label>System Award Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Grant_Scheme__c.object
<CustomObject>
    <label>Grant Scheme</label>
    <nameField>
        <displayFormat>SCH-{000000000}</displayFormat>
        <label>System Scheme Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Cabinet office backup/src/classes/GrantSchemeConfirmDeleteControllerTest.cls
/******************************************************************************************
@Author         Ric Dayrit
@Date           07/03/2016
@Project        Cloud Sherpas Cabinet Office Data Source
@Description    This is the unit test for GrantSchemeConfirmDeleteController class
*******************************************************************************************/
@isTest
private class GrantSchemeConfirmDeleteControllerTest{

	@testSetup()
    static void setupTestData(){
        TestDataFactory testFactory = new TestDataFactory();
        testFactory.insertReferenceData();
        
        Account department1 = testFactory.createAccount('Department1','NEW_CPID_Department1');
        department1.Primary_Address_1__c = 'Unit 1, Horse Guards Rd';
        department1.Primary_Address_2__c = 'HM Treasury';
        department1.Primary_City__c = 'London';
        department1.Primary_County__c = 'Greater London';
        department1.Primary_Country__c = 'United Kingdom';
        department1.Primary_Postal_Code__c = 'SW1A 2HQ';
        insert department1;

        Account acctStandardUser = testFactory.createAccount('StandardUser','StandardUser');
        insert acctStandardUser;  

        User dept1SuperUser1 = testFactory.setupBasicUser(department1, 'SuperUserContact1', 'Data Solution Portal - Super User');
        insert dept1SuperUser1;
        User standardUser = testFactory.setupBasicUser(acctStandardUser ,'BasicUserContact','Data Solution Portal - User');
        insert standardUser;

        System.runAs(dept1SuperUser1){
            Grant_Scheme__c grantSchemeCreatedByDept1SuperUser1 = testFactory.createGrantScheme(
            	department1, 'Test Grant Award NonAdminRecord01', testFactory.testCOFOGLevel
            );
            insert grantSchemeCreatedByDept1SuperUser1;
            Grant_Award__c grantAwardCreatedByDept1SuperUser1 = testFactory.createGrantAward(
            	'Test Grant Award AdminRecord', department1, grantSchemeCreatedByDept1SuperUser1
            );
            grantAwardCreatedByDept1SuperUser1.Postal_Code_Geo_Location__Latitude__s = 51.503648907772100;
            grantAwardCreatedByDept1SuperUser1.Postal_Code_Geo_Location__Longitude__s = -0.126638914084856;
            grantAwardCreatedByDept1SuperUser1.Postal_Code_Region__c = 'London';
            grantAwardCreatedByDept1SuperUser1.Postal_Code_Parliamentary_Constituency__c = 'Islington North';
            grantAwardCreatedByDept1SuperUser1.Is_Postal_Code_Valid__c = true;
            grantAwardCreatedByDept1SuperUser1.Has_Postal_Code_Been_Checked__c = true;
            grantAwardCreatedByDept1SuperUser1.Total_Amount_in_funding_agreement__c = 100;
            Date startOfThisYearFY = Date.newInstance(Date.today().year(), 4, 1);
            grantAwardCreatedByDept1SuperUser1.Award_Start_Date__c = startOfThisYearFY.addMonths(-8);
            grantAwardCreatedByDept1SuperUser1.Award_End_Date__c = startOfThisYearFY.addMonths(-2);
            insert grantAwardCreatedByDept1SuperUser1;
        }
    }

    @isTest
    static void testGetAvailableRegions(){
        GrantSchemeConfirmDeleteController controller = new GrantSchemeConfirmDeleteController(
            new ApexPages.StandardController([SELECT Id FROM Grant_Scheme__c LIMIT 1])
        );
        System.assertEquals(1, controller.getCountOfRelatedGrantAwards());
    }
    @isTest
    static void testDeleteSuccess(){
        GrantSchemeConfirmDeleteController controller = new GrantSchemeConfirmDeleteController(
            new ApexPages.StandardController([SELECT Id FROM Grant_Scheme__c LIMIT 1])
        );
        System.assertNotEquals(null, controller.deleteAll());
    }
	/**@isTest
	//static void testDeleteFail(){
      //  User dept1SuperUser1 = [SELECT Id FROM User WHERE Email = 'SuperUserContact1@cabinetoffice.gov.uk' LIMIT 1][0];
        Grant_Scheme__c grantScheme = [SELECT Id FROM Grant_Scheme__c LIMIT 1][0];
        Test.setCreatedDate(grantScheme.Id, Datetime.newInstance(2011, 3, 3));
        System.runAs(dept1SuperUser1){
            Test.startTest();
                GrantSchemeConfirmDeleteController controller = new GrantSchemeConfirmDeleteController(
                    new ApexPages.StandardController(grantScheme)
                );
                System.assertEquals(null, controller.deleteAll());
            Test.stopTest();
        }
	}**/

    @isTest
    static void testShowDeleteButtonShowAdminUser() {
        GrantSchemeConfirmDeleteController controller = new GrantSchemeConfirmDeleteController(
            new ApexPages.StandardController([SELECT Id FROM Grant_Scheme__c LIMIT 1])
        );
        System.assertEquals(true, controller.getShowDeleteButton());
    }

    @isTest
    static void testShowDeleteButtonHidden() {
        User standardUser = [SELECT Id FROM User WHERE Email = 'BasicUserContact@cabinetoffice.gov.uk' LIMIT 1][0];
        System.runAs(standardUser) {
            Test.startTest();
                GrantSchemeConfirmDeleteController controller = new GrantSchemeConfirmDeleteController(
                    new ApexPages.StandardController([SELECT Id FROM Grant_Scheme__c LIMIT 1])
                );
                System.assertEquals(false, controller.getShowDeleteButton());
            Test.stopTest();
        }
    }

}