src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CPID_from_OSCAR__c</fullName>
        <description>This is an external id that will be used for the data upload process.</description>
        <externalId>true</externalId>
        <inlineHelpText>Counter-Party Identifier Code (CPID). The Treasury produced a list of all bodies within the Whole of Government Accounts boundary (WGA). Each WGA body is issued by the Treasury with a unique CPID code. To be provided if applicable.</inlineHelpText>
        <label>CPID (from OSCAR)</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Charities_Commission_Number__c</fullName>
        <description>This is an external id that will be used for the data upload process.</description>
        <externalId>true</externalId>
        <inlineHelpText>Registered charity number for the organisation. To be provided if applicable.</inlineHelpText>
        <label>Charities Commission Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Companies_House_Number__c</fullName>
        <description>This is an external id that will be used for the data upload process.</description>
        <externalId>true</externalId>
        <inlineHelpText>This can also be called the Company Registration Number (CRN) and is allocated by Companies House on registration of a company. To be provided if applicable.</inlineHelpText>
        <label>Companies House Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>DUNS_Number__c</fullName>
        <description>This is an external id that will be used for the data upload process.</description>
        <externalId>true</externalId>
        <inlineHelpText>The Data Universal Number System -  a proprietary system developed and regulated by Dun &amp; Bradstreet (D&amp;B) that assigns a unique numeric identifier, referred to as a &quot;DUNS number&quot; to a single business entity. To be provided if applicable.</inlineHelpText>
        <label>DUNS Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ISNI__c</fullName>
        <description>This is an external id that will be used for the data upload process.</description>
        <externalId>true</externalId>
        <inlineHelpText>International Standard Name Identifier. ISNI is the ISO certified global standard number for identifying the millions of contributors to creative works and those active in their distribution. To be provided if applicable.</inlineHelpText>
        <label>ISNI</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>International_ID__c</fullName>
        <description>This is the internation Id which is used as the external id for the organisation.</description>
        <inlineHelpText>this is an ID for international organisations that might not have any of the above IDs</inlineHelpText>
        <label>International ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_ID__c</fullName>
        <description>This is an external id that will be used for the data upload process.</description>
        <externalId>true</externalId>
        <inlineHelpText>If organisation has another internal system ID that a department is storing, this can be provided here. 
In order for the system to de-duplicate one of the IDs below is necessary. If none are available, please include any other reference number.</inlineHelpText>
        <label>Other ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Address_1__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The first line of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_2__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The second line of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_City__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The city of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Country__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The country of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abu Dhabi</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Ajman</fullName>
                </value>
                <value>
                    <fullName>Akrotiri</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Ascension</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Baker Island</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>United Kingdom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_County__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The county of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Postal_Code__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The Location based data report is based on the accuracy of this postcode. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VAT_Reg_no__c</fullName>
        <description>This is an external id that will be used for the data upload process.</description>
        <externalId>true</externalId>
        <inlineHelpText>Tax registration number. To be provided if applicable.</inlineHelpText>
        <label>VAT Reg no</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Grant_Award__c.object
<CustomObject>
    <fields>
        <fullName>Grant_Scheme__c</fullName>
        <description>This is the parent scheme for this award</description>
        <inlineHelpText>This is the System Scheme Reference No and clicking it will take you back to the Scheme that this award belong to.</inlineHelpText>
        <label>Grant Scheme</label>
        <referenceTo>Grant_Scheme__c</referenceTo>
        <relationshipLabel>Grant Awards</relationshipLabel>
        <relationshipName>Grant_Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Grant Award</label>
    <nameField>
        <displayFormat>GA-{000000}</displayFormat>
        <label>System Award Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Grant_Scheme__c.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>The date the Grant Scheme commences</inlineHelpText>
        <label>Scheme start date</label>
        <type>Date</type>
    </fields>
    <label>Grant Scheme</label>
    <nameField>
        <displayFormat>SCH-{000000000}</displayFormat>
        <label>System Scheme Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Intermediary__c.object
<CustomObject>
    <description>This is the organisation which carries out the intermediary role</description>
    <fields>
        <fullName>Grant_Scheme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the related grant scheme</description>
        <label>System Scheme Reference No</label>
        <referenceTo>Grant_Scheme__c</referenceTo>
        <relationshipLabel>Intermediaries</relationshipLabel>
        <relationshipName>Intermediaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Intermediary</label>
    <nameField>
        <displayFormat>INT-{00000000}</displayFormat>
        <label>Intermediary Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intermediaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Cabinet office backup/src/classes/AccountMergeControllerTest.cls
/******************************************************************************************
@Author         Daniel Lagar
@Date           23/05/2017
@Project        Cloud Sherpas Cabinet Office Data Source
@Description    test class for the AccountMergeController extension.
*******************************************************************************************/
@isTest
public class AccountMergeControllerTest {
    //data set up accounts, schemes, award and intermediaries using the TestDataFactory Class.
    @testSetup public static void setup() {
        TestDataFactory testFactory = new TestDataFactory();
        testFactory.insertReferenceData();
        
        //the account used as the current parent.
        Account department1 = testFactory.createAccount('Department1','NEW_CPID_Department1');
            department1.Primary_Address_1__c = 'Unit 1, Horse Guards Rd';
            department1.Primary_Address_2__c = 'HM Treasury';
            department1.Primary_City__c = 'London';
            department1.Primary_County__c = 'Greater London';
            department1.Primary_Country__c = 'United Kingdom';
            department1.Primary_Postal_Code__c = 'SW1A 2HQ';
            department1.CPID_from_OSCAR__c = '20075';
            department1.Companies_House_Number__c = '6855521';
            department1.Charities_Commission_Number__c = '1117229';
            department1.VAT_Reg_no__c = '331333334';
            department1.DUNS_Number__c = '2341';
            department1.ISNI__c = '35235';
            department1.International_ID__c = '534532';
            department1.Other_ID__c = 'SP-G15-A07-09';
        database.insert(department1);
        
        //the account to be used as the new parent
        Account department2 = testFactory.createAccount('Department2','NEW_CPID_Department12');
            department1.Primary_Address_1__c = 'Unit 12, Horse Guards Rd';
            department1.Primary_Address_2__c = 'HM Treasury1';
            department1.Primary_City__c = 'London2';
            department1.Primary_County__c = 'Greater London';
            department1.Primary_Country__c = 'United Kingdom';
            department1.Primary_Postal_Code__c = 'SW1A 3HQ';
            department1.CPID_from_OSCAR__c = '20075';
            department1.Companies_House_Number__c = '6855521';
            department1.Charities_Commission_Number__c = '1117229';
            department1.VAT_Reg_no__c = '331333334';
            department1.DUNS_Number__c = '2341';
            department1.ISNI__c = '35235';
            department1.International_ID__c = '534532';
            department1.Other_ID__c = 'SP-G15-A07-09';
        database.insert(department2);
        
        //create department1's grant scheme
        Grant_Scheme__c grantSchemeCreatedByDept1SuperUser1 = testFactory.createGrantScheme(
            department1, 'Test Grant Award NonAdminRecord01', testFactory.testCOFOGLevel);
            grantSchemeCreatedByDept1SuperUser1.Start_Date__C = date.valueOf('2016-04-01');
            grantSchemeCreatedByDept1SuperUser1.Duration__C = '5';
            grantSchemeCreatedByDept1SuperUser1.Risk_Profile__c ='Medium';
            grantSchemeCreatedByDept1SuperUser1.Senior_Responsible_Officer_Full_Name__c = 'test';
            grantSchemeCreatedByDept1SuperUser1.Scheme_Value__c = 2234;
            grantSchemeCreatedByDept1SuperUser1.Contact_email_address__c ='test@test.com';
            grantSchemeCreatedByDept1SuperUser1.Public_funding_source__c ='NATO';
            grantSchemeCreatedByDept1SuperUser1.Primary_Purpose__c ='Research & Innovation';
            grantSchemeCreatedByDept1SuperUser1.Allocation_Method__c = 'Formula';
            grantSchemeCreatedByDept1SuperUser1.Target_Location__c = 'England';
            grantSchemeCreatedByDept1SuperUser1.Recipient_Sector__c = 'Central Government';
            grantSchemeCreatedByDept1SuperUser1.Considered_by_the_Grants_Advice_Panel__c ='No';
            grantSchemeCreatedByDept1SuperUser1.Capital_Resource__c ='Capital';
            grantSchemeCreatedByDept1SuperUser1.Related_policy_objective__c ='test';
            grantSchemeCreatedByDept1SuperUser1.Funder__c =department1.id;
        database.insert(grantSchemeCreatedByDept1SuperUser1);
        
        //create department1's Intermediary
        Intermediary__c testIntermediary = testFactory.createIntermediary(department1, grantSchemeCreatedByDept1SuperUser1);
            testIntermediary.Intermediary_Organisation__c = department1.id;
        database.insert(testIntermediary);
        
        //create department1's Award
        Grant_Award__c testGrantAward = testFactory.createGrantAward('GrantAward1', department1,grantSchemeCreatedByDept1SuperUser1);
            testGrantAward.Recipient__c = department1.id;
            testGrantAward.Grant_Award_Objective__c = 'test';
        database.insert(testGrantAward);
    }
        //test method to test the search funtion.
        public static testMethod void TestsearchAccount(){
            //get the accounts from the test set up.
            account department1 = [select id, name from account where name = 'Department1' limit 1];
            account department2 = [select id, name from account where name = 'Department2' limit 1];
            //instanciate the page
            PageReference pageRef = Page.AccountMergePage;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('id', department1.id);
            ApexPages.StandardController stdController = new ApexPages.StandardController(department1);
            AccountMergeController ext = new AccountMergeController(stdController);
            ApexPages.currentPage().getParameters().put('selected', department2.id);
            
            test.startTest();
                ext.setComp();
                ext.searchAccount();
            test.stopTest();

    }
        //test method to test the re-parent funtionality.
        public static testMethod void TestreParent(){
            //get the accounts from the test set up.
            account department1 = [select id, name from account where name = 'Department1' limit 1];
            account department2 = [select id, name from account where name = 'Department2' limit 1];
            //instanciate the page
            PageReference pageRef = Page.AccountMergePage;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('id', department1.id);
            ApexPages.StandardController stdController = new ApexPages.StandardController(department1);
            AccountMergeController ext = new AccountMergeController(stdController);
            ApexPages.currentPage().getParameters().put('selected', department2.id);
            test.startTest();
                ext.setComp();
                ext.reParent();
            test.stopTest();
    }
        //test method to test the re-parent funtionality when no parent account is selected.
        public static testMethod void TestNoAccountSelected(){
            account department1 = [select id, name from account where name = 'Department1' limit 1];
            account department2 = [select id, name from account where name = 'Department2' limit 1];
            PageReference pageRef = Page.AccountMergePage;
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('id', department1.id);
            ApexPages.StandardController stdController = new ApexPages.StandardController(department1);
            AccountMergeController ext = new AccountMergeController(stdController);
            test.startTest();
                ext.reParent();
            test.stopTest();
    }   


}