src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Address_1__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The first line of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_2__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The second line of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_City__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The city of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Country__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The country of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abu Dhabi</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Ajman</fullName>
                </value>
                <value>
                    <fullName>Akrotiri</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Ascension</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Baker Island</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>United Kingdom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_County__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The county of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Postal_Code__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The Location based data report is based on the accuracy of this postcode. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Grant_Award__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Payment__c</fullName>
        <inlineHelpText>The actual payment amount that has been given to the Recipient(s). This is to be filled in only as a total amount, once the last payment has been made, as one activity.</inlineHelpText>
        <label>Actual Payment</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Award_End_Date__c</fullName>
        <inlineHelpText>The date the grant closes, as per grant award agreement or letter.</inlineHelpText>
        <label>Award End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Award_Start_Date__c</fullName>
        <inlineHelpText>The date the grant was issued, as per grant award agreement or letter.</inlineHelpText>
        <label>Award Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grant_Scheme__c</fullName>
        <description>This is the parent scheme for this award</description>
        <inlineHelpText>This is the System Scheme Reference No and clicking it will take you back to the Scheme that this award belong to.</inlineHelpText>
        <label>Grant Scheme</label>
        <referenceTo>Grant_Scheme__c</referenceTo>
        <relationshipLabel>Grant Awards</relationshipLabel>
        <relationshipName>Grant_Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Frequency__c</fullName>
        <inlineHelpText>When the payments are made to recipients. Upfront/ End = Payments are made at beginning/ end of grant lifecycle. Instalment payments are made at regular intervals throughout grant lifecycle. Ad-hoc payments are at irregular times.</inlineHelpText>
        <label>Payment Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ad-hoc payments</fullName>
                </value>
                <value>
                    <fullName>Upfront payments</fullName>
                </value>
                <value>
                    <fullName>End payments</fullName>
                </value>
                <value>
                    <fullName>Instalment payments</fullName>
                </value>
                <value>
                    <fullName>Milestone payments</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recipient_Secondary_Postal_Code__c</fullName>
        <inlineHelpText>The Location based data report is based on the accuracy of this postcode. If a grant award is going to a different address than the one already stored for the Recipient Organisation, then populate the postcode of the organisation&apos;s address.</inlineHelpText>
        <label>Recipient Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Grant Award</label>
    <nameField>
        <displayFormat>GA-{000000}</displayFormat>
        <label>System Award Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Grant_Scheme__c.object
<CustomObject>
    <label>Grant Scheme</label>
    <nameField>
        <displayFormat>SCH-{000000000}</displayFormat>
        <label>System Scheme Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SendIncompleteGrantReminder_Test.cls
/******************************************************************************************
@Author         Bhushan Sukumar
@Date           30 Mar 2016
@Description    This is the unit test for SendIncompleteGrantReminder batch class
*******************************************************************************************/

@isTest
private class SendIncompleteGrantReminder_Test {

    static User dept1SuperUser1;
    static user dept1SuperUser1Inactive;

    @isTest static void testSendIncompleteGrantReminderExecute() {
        Test.startTest();
        SendIncompleteGrantReminder batchJob = new SendIncompleteGrantReminder();
        Id batchId = Database.executeBatch(batchJob);
        system.assertNotEquals(null, batchId);
        List<Grant_Award__c> awards = [SELECT Id,
                                       CreatedById, Actual_Payment__c
                                       , Payment_Frequency__c
                                       , Award_Start_Date__c
                                       , Award_End_Date__c
                                       , CreatedBy.IsActive
                                       FROM Grant_Award__c
                                       WHERE Actual_Payment__c = null
                                               AND ((Payment_Frequency__c = : Constant.UPFRONT_PAYMENT
                                                       AND Award_Start_Date__c = LAST_MONTH)
                                                       OR ((Payment_Frequency__c = : Constant.INSTALMENT_PAYMENTS
                                                               OR Payment_Frequency__c = : Constant.END_PAYMENT)
                                                               AND Award_End_Date__c = LAST_MONTH))];
        batchJob.execute((Database.BatchableContext)null, awards);
        Test.stopTest();
    }

    @isTest
    static void testSendIncompleteGrantReminderWithGrantReminderUpdated() {
        Test.startTest();
        SendIncompleteGrantReminder batchJob = new SendIncompleteGrantReminder();
        Id batchId = Database.executeBatch(batchJob);
        system.assertNotEquals(null, batchId);
        List<Grant_Award__c> awards = [SELECT Id,
                                       CreatedById, Actual_Payment__c
                                       , Payment_Frequency__c
                                       , Award_Start_Date__c
                                       , Award_End_Date__c
                                       , CreatedBy.IsActive
                                       FROM Grant_Award__c
                                       WHERE Actual_Payment__c = null
                                               AND ((Payment_Frequency__c = : Constant.UPFRONT_PAYMENT
                                                       AND Award_Start_Date__c = LAST_MONTH)
                                                       OR ((Payment_Frequency__c = : Constant.INSTALMENT_PAYMENTS
                                                               OR Payment_Frequency__c = : Constant.END_PAYMENT)
                                                               AND Award_End_Date__c = LAST_MONTH))];
        batchJob.execute((Database.BatchableContext)null, awards);
        Test.stopTest();
    }

    @isTest
    static void testSendIncompleteGrantReminderWithInactiveUser() {
        Test.startTest();
        SendIncompleteGrantReminder batchJob = new SendIncompleteGrantReminder();
        Id batchId = Database.executeBatch(batchJob);
        system.assertNotEquals(null, batchId);
        List<Grant_Award__c> awards = [SELECT Id,
                                       CreatedById, Actual_Payment__c
                                       , Payment_Frequency__c
                                       , Award_Start_Date__c
                                       , Award_End_Date__c
                                       , CreatedBy.IsActive
                                       FROM Grant_Award__c
                                       WHERE Actual_Payment__c = null
                                               AND ((Payment_Frequency__c = : Constant.UPFRONT_PAYMENT
                                                       AND Award_Start_Date__c = LAST_MONTH)
                                                       OR ((Payment_Frequency__c = : Constant.INSTALMENT_PAYMENTS
                                                               OR Payment_Frequency__c = : Constant.END_PAYMENT)
                                                               AND Award_End_Date__c = LAST_MONTH))];
        batchJob.execute((Database.BatchableContext)null, awards);
        Test.stopTest();
    }

    @testSetup()
    static void setupTesData() {
        TestDataFactory testFactory = new TestDataFactory();
        testFactory.insertReferenceData();
        Account department1 = testFactory.createAccount('Department1', 'NEW_CPID_Department1');
        department1.Primary_Address_1__c = 'Unit 1, Horse Guards Rd';
        department1.Primary_Address_2__c = 'HM Treasury';
        department1.Primary_City__c = 'London';
        department1.Primary_County__c = 'Greater London';
        department1.Primary_Country__c = 'United Kingdom';
        department1.Primary_Postal_Code__c = 'SW1A 2HQ';
        insert department1;
        dept1SuperUser1 = testFactory.setupBasicUser(department1 , 'SuperUserContact1', 'Data Solution Portal - Super User');
        insert dept1SuperUser1;
        System.runAs(dept1SuperUser1) {
            Grant_Scheme__c grantSchemeCreatedByDept1SuperUser1 = testFactory.createGrantScheme(
                        department1, 'Test Grant Award NonAdminRecord01', testFactory.testCOFOGLevel
                    );
            insert grantSchemeCreatedByDept1SuperUser1;
            Grant_Award__c grantAwardCreatedByDept1SuperUser1 = testFactory.createGrantAward(
                        'Test Grant Award AdminRecord', department1, grantSchemeCreatedByDept1SuperUser1
                    );
            grantAwardCreatedByDept1SuperUser1.Recipient_Secondary_Postal_Code__c = 'SW1A         2HQ';
            insert grantAwardCreatedByDept1SuperUser1;

            grantAwardCreatedByDept1SuperUser1.Payment_Frequency__c = Constant.UPFRONT_PAYMENT;
            grantAwardCreatedByDept1SuperUser1.Award_Start_Date__c = Date.today() - 45;

            update grantAwardCreatedByDept1SuperUser1;

            Grant_Award__c grantAward2CreatedByDept1SuperUser1 = testFactory.createGrantAward(
                        'Test Grant Award AdminRecord2', department1, grantSchemeCreatedByDept1SuperUser1
                    );
            grantAward2CreatedByDept1SuperUser1.Recipient_Secondary_Postal_Code__c = 'SW1A         2HQ';
            grantAward2CreatedByDept1SuperUser1.Payment_Frequency__c = Constant.UPFRONT_PAYMENT;
            grantAward2CreatedByDept1SuperUser1.Award_Start_Date__c = Date.today() - 45;
            insert grantAward2CreatedByDept1SuperUser1;

            if ((Date.today().month() - grantAward2CreatedByDept1SuperUser1.Award_Start_Date__c.month()) != 1) {
                grantAward2CreatedByDept1SuperUser1.Award_Start_Date__c += 15;
            }

            update grantAward2CreatedByDept1SuperUser1;
        }

        dept1SuperUser1Inactive = testFactory.setupBasicUser(department1 , 'SuperUserContactInvalid', 'Data Solution Portal - Super User');
        insert dept1SuperUser1Inactive;

        System.runAs(dept1SuperUser1Inactive) {
            Grant_Scheme__c grantSchemeCreatedByDept1SuperUser1 = testFactory.createGrantScheme(
                        department1, 'Test Grant Award NonAdminRecord01', testFactory.testCOFOGLevel
                  );
            insert grantSchemeCreatedByDept1SuperUser1;

            Grant_Award__c grantAward2CreatedByDept1SuperUser1 = testFactory.createGrantAward(
                        'Test Grant Award AdminRecord2', department1, grantSchemeCreatedByDept1SuperUser1
                    );
            grantAward2CreatedByDept1SuperUser1.Recipient_Secondary_Postal_Code__c = 'SW1A         2HQ';
            grantAward2CreatedByDept1SuperUser1.Payment_Frequency__c = Constant.UPFRONT_PAYMENT;
            grantAward2CreatedByDept1SuperUser1.Award_Start_Date__c = Date.today() - 45;
            insert grantAward2CreatedByDept1SuperUser1;

            if ((Date.today().month() - grantAward2CreatedByDept1SuperUser1.Award_Start_Date__c.month()) != 1) {
                grantAward2CreatedByDept1SuperUser1.Award_Start_Date__c += 15;
            }

            update grantAward2CreatedByDept1SuperUser1;
        }

        System.runAs(dept1SuperUser1) {
            dept1SuperUser1Inactive.isActive = false;
            update dept1SuperUser1Inactive;
        }
    }
}