src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Address_1__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The first line of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_2__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The second line of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_City__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The city of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Country__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The country of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abu Dhabi</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Ajman</fullName>
                </value>
                <value>
                    <fullName>Akrotiri</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Ascension</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Baker Island</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>United Kingdom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_County__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The county of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Postal_Code__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The Location based data report is based on the accuracy of this postcode. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Grant_Award__c.object
<CustomObject>
    <fields>
        <fullName>Grant_Scheme__c</fullName>
        <description>This is the parent scheme for this award</description>
        <inlineHelpText>This is the System Scheme Reference No and clicking it will take you back to the Scheme that this award belong to.</inlineHelpText>
        <label>Grant Scheme</label>
        <referenceTo>Grant_Scheme__c</referenceTo>
        <relationshipLabel>Grant Awards</relationshipLabel>
        <relationshipName>Grant_Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Has_Postal_Code_Been_Checked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates if the postcode has been validated or not</description>
        <label>Has Postal Code Been Checked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Postal_Code_Valid__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates if the value for this post code is valid or not.</description>
        <inlineHelpText>This checkbox indicates if the value for this post code is valid or not.</inlineHelpText>
        <label>Is Postal Code Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Validation_Error_Message__c</fullName>
        <description>These is the error message returned from the post code validation error.</description>
        <inlineHelpText>These is the error message returned from the post code validation error.</inlineHelpText>
        <label>Postal Code Validation Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Recipient_Secondary_Postal_Code__c</fullName>
        <inlineHelpText>The Location based data report is based on the accuracy of this postcode. If a grant award is going to a different address than the one already stored for the Recipient Organisation, then populate the postcode of the organisation&apos;s address.</inlineHelpText>
        <label>Recipient Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Grant Award</label>
    <nameField>
        <displayFormat>GA-{000000}</displayFormat>
        <label>System Award Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Grant_Scheme__c.object
<CustomObject>
    <label>Grant Scheme</label>
    <nameField>
        <displayFormat>SCH-{000000000}</displayFormat>
        <label>System Scheme Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Cabinet office backup/src/classes/GrantAwardPostalCodeValidatorTest.cls
/******************************************************************************************
@Author         Hamed Izadpanah
@Date           18/02/2015
@Project        Cloud Sherpas Cabinet Office Data Source
@Description    This is the test unit for GrantAwardPostalCodeValidator class
*******************************************************************************************/
@isTest
private class GrantAwardPostalCodeValidatorTest{

	@testSetup()
    static void setupTestData(){
        TestDataFactory testFactory = new TestDataFactory();
        testFactory.insertReferenceData();
        Account department1 = testFactory.createAccount('Department1','NEW_CPID_Department1');
        department1.Primary_Address_1__c = 'Unit 1, Horse Guards Rd';
        department1.Primary_Address_2__c = 'HM Treasury';
        department1.Primary_City__c = 'London';
        department1.Primary_County__c = 'Greater London';
        department1.Primary_Country__c = 'United Kingdom';
        department1.Primary_Postal_Code__c = 'SW1A 2HQ';
        insert department1;
        User dept1SuperUser1 = testFactory.setupBasicUser(department1 ,'SuperUserContact1','Data Solution Portal - Super User');
        insert dept1SuperUser1;
        System.runAs(dept1SuperUser1){
            Grant_Scheme__c grantSchemeCreatedByDept1SuperUser1 = testFactory.createGrantScheme(
            	department1, 'Test Grant Award NonAdminRecord01', testFactory.testCOFOGLevel
            );
            insert grantSchemeCreatedByDept1SuperUser1;
            Grant_Award__c grantAwardCreatedByDept1SuperUser1 = testFactory.createGrantAward(
            	'Test Grant Award AdminRecord', department1, grantSchemeCreatedByDept1SuperUser1
            );
            grantAwardCreatedByDept1SuperUser1.Recipient_Secondary_Postal_Code__c = 'SW1A         2HQ';
            insert grantAwardCreatedByDept1SuperUser1;
        }
    }


	@isTest
	static void testValidateValidPostCodeWithExecute(){
		PostCodesIO.PostCodeResult mockResult = PostCodesIO.generateMockResult();
		PostCodesIO.ResponseWrapper responseWrapper = new PostCodesIO.ResponseWrapper();
		responseWrapper.status = 200;
		responseWrapper.result = mockResult;
		BasicHttpCalloutMock calloutMock = new BasicHttpCalloutMock(
			200,
			'OK',
			JSON.serializePretty(responseWrapper),
			new Map<String, String>()
		);
		Test.setMock(HttpCalloutMock.class, calloutMock);


		List<Grant_Award__c> createdGrantAwards = [
			SELECT Recipient_Secondary_Postal_Code__c,
			Postal_Code_Validation_Error_Message__c, 
			Is_Postal_Code_Valid__c, Has_Postal_Code_Been_Checked__c
			FROM Grant_Award__c
		];
		System.assertEquals(1, createdGrantAwards.size());
		System.assertEquals(null, createdGrantAwards[0].Postal_Code_Validation_Error_Message__c);
		System.assertEquals('SW1A         2HQ', createdGrantAwards[0].Recipient_Secondary_Postal_Code__c);
		System.assertEquals(false, createdGrantAwards[0].Is_Postal_Code_Valid__c);
		System.assertEquals(false, createdGrantAwards[0].Has_Postal_Code_Been_Checked__c);
		GrantAwardPostalCodeValidator postalCodeValidator = new GrantAwardPostalCodeValidator();
		postalCodeValidator.execute(null, createdGrantAwards);
		System.assertEquals(1, createdGrantAwards.size());
		System.assertEquals(null, createdGrantAwards[0].Postal_Code_Validation_Error_Message__c);
		System.assertEquals('SW1A 2HQ', createdGrantAwards[0].Recipient_Secondary_Postal_Code__c);
		
		System.assertEquals(true, createdGrantAwards[0].Is_Postal_Code_Valid__c);
		System.assertEquals(true, createdGrantAwards[0].Has_Postal_Code_Been_Checked__c);
	}

	@isTest
	static void testValidateValidPostCodeWithBatchProcess(){
		PostCodesIO.PostCodeResult mockResult = PostCodesIO.generateMockResult();
		PostCodesIO.ResponseWrapper responseWrapper = new PostCodesIO.ResponseWrapper();
		responseWrapper.status = 200;
		responseWrapper.result = mockResult;
		BasicHttpCalloutMock calloutMock = new BasicHttpCalloutMock(
			200,
			'OK',
			JSON.serializePretty(responseWrapper),
			new Map<String, String>()
		);
		Test.setMock(HttpCalloutMock.class, calloutMock);


		List<Grant_Award__c> createdGrantAwards = [
			SELECT Recipient_Secondary_Postal_Code__c,
			Postal_Code_Validation_Error_Message__c, 
			Is_Postal_Code_Valid__c, Has_Postal_Code_Been_Checked__c
			FROM Grant_Award__c
		];
		System.assertEquals(1, createdGrantAwards.size());
		System.assertEquals(null, createdGrantAwards[0].Postal_Code_Validation_Error_Message__c);
		System.assertEquals('SW1A         2HQ', createdGrantAwards[0].Recipient_Secondary_Postal_Code__c);
		System.assertEquals(false, createdGrantAwards[0].Is_Postal_Code_Valid__c);
		System.assertEquals(false, createdGrantAwards[0].Has_Postal_Code_Been_Checked__c);
		Test.startTest();
			GrantAwardPostalCodeValidator postalCodeValidator = new GrantAwardPostalCodeValidator();
			Database.executeBatch(postalCodeValidator, 10);
		Test.stopTest();
		createdGrantAwards = [
			SELECT Recipient_Secondary_Postal_Code__c,
			Postal_Code_Validation_Error_Message__c, 
			Is_Postal_Code_Valid__c, Has_Postal_Code_Been_Checked__c
			FROM Grant_Award__c
		];
		System.assertEquals(1, createdGrantAwards.size());
		System.assertEquals(null, createdGrantAwards[0].Postal_Code_Validation_Error_Message__c);
		System.assertEquals('SW1A 2HQ', createdGrantAwards[0].Recipient_Secondary_Postal_Code__c);
	}
	@isTest
	static void testValidateValidPostCodeWithSchedule(){
		PostCodesIO.PostCodeResult mockResult = PostCodesIO.generateMockResult();
		PostCodesIO.ResponseWrapper responseWrapper = new PostCodesIO.ResponseWrapper();
		responseWrapper.status = 200;
		responseWrapper.result = mockResult;
		BasicHttpCalloutMock calloutMock = new BasicHttpCalloutMock(
			200,
			'OK',
			JSON.serializePretty(responseWrapper),
			new Map<String, String>()
		);
		Test.setMock(HttpCalloutMock.class, calloutMock);


		List<Grant_Award__c> createdGrantAwards = [
			SELECT Recipient_Secondary_Postal_Code__c,
			Postal_Code_Validation_Error_Message__c, 
			Is_Postal_Code_Valid__c, Has_Postal_Code_Been_Checked__c
			FROM Grant_Award__c
		];
		System.assertEquals(1, createdGrantAwards.size());
		System.assertEquals(null, createdGrantAwards[0].Postal_Code_Validation_Error_Message__c);
		System.assertEquals('SW1A         2HQ', createdGrantAwards[0].Recipient_Secondary_Postal_Code__c);
		System.assertEquals(false, createdGrantAwards[0].Is_Postal_Code_Valid__c);
		System.assertEquals(false, createdGrantAwards[0].Has_Postal_Code_Been_Checked__c);
		Test.startTest();
			String CRON_EXP = '0 0 0 3 9 ? 2099';
			String jobId = System.schedule('TEST SCHEDULE BATCH', CRON_EXP, new GrantAwardPostalCodeValidator());
			CronTrigger ct = [
				SELECT Id, CronExpression, TimesTriggered, NextFireTime
				FROM CronTrigger WHERE id = :jobId
			];
			System.assertEquals(0, ct.TimesTriggered);
		Test.stopTest();
	}
}