src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Address_1__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The first line of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_2__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The second line of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_City__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The city of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Country__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The country of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abu Dhabi</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Ajman</fullName>
                </value>
                <value>
                    <fullName>Akrotiri</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Ascension</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Baker Island</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_County__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The county of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Postal_Code__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The Location based data report is based on the accuracy of this postcode. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recipient</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CSV_Upload_Mapping_Column__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is the CSV Upload mapping for the CSV upload functionality.</description>
    <fields>
        <fullName>Accept_Multi_Values__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This value shows if the target mapped to field is a multi picklist value or a single picklist vlaue</description>
        <inlineHelpText>This value shows if the target mapped to field is a multi picklist value or a single picklist vlaue</inlineHelpText>
        <label>Accept Multi Values</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSV_Upload_Recipient_Type__c</fullName>
        <description>This is the recipient type for csv upload process.</description>
        <inlineHelpText>This is the recipient type for csv upload process.</inlineHelpText>
        <label>CSV Upload Recipient Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSV_Upload_Type__c</fullName>
        <description>This is the type of CSV upload that needs to be performed. Possible option is Grant Award</description>
        <inlineHelpText>This is the type of CSV upload that needs to be performed. Possible option is Grant Award</inlineHelpText>
        <label>CSV Upload Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id_Type_Column__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This column is used as external id type column and should not be mapped directly to another field.</description>
        <inlineHelpText>This column is used as external id type column and should not be mapped directly to another field.</inlineHelpText>
        <label>External Id Type Column</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mapped_From_Field__c</fullName>
        <description>This is the From field in the CSV file. This value needs to be exactly the same as it appears on CSV.</description>
        <inlineHelpText>This is the From field in the CSV file. This value needs to be exactly the same as it appears on CSV.</inlineHelpText>
        <label>Mapped From Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mapped_To_Field__c</fullName>
        <description>This is the From to in the CSV file. This value needs to be exactly the same as it is on the Target Object</description>
        <inlineHelpText>This is the From to in the CSV file. This value needs to be exactly the same as it is on the Target Object</inlineHelpText>
        <label>Mapped To Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Not_Found_Error_Message__c</fullName>
        <description>This error message is shown when the Record Locator Query doesn&apos;t return any records.</description>
        <inlineHelpText>This error message is shown when the Record Locator Query doesn&apos;t return any records.</inlineHelpText>
        <label>Not Found Error Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Query_Result_Id_Mapped_to_Field__c</fullName>
        <description>This is the field that will be used to replace the Mapped to field.</description>
        <inlineHelpText>This is the field that will be used to replace the Mapped to field.</inlineHelpText>
        <label>Query Result Id Mapped to Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Locator_Query__c</fullName>
        <description>This field holds the query string to retrieve the related record from the database.</description>
        <inlineHelpText>This field holds the query string to retrieve the related record from the database.</inlineHelpText>
        <label>Record Locator Query</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox shows if the column is a mandatory field for the input CSV file.</description>
        <inlineHelpText>This checkbox shows if the column is a mandatory field for the input CSV file.</inlineHelpText>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Run_SObject_Creator_On_Record_Not_Found__c</fullName>
        <description>This field records the creator that needs to be run when the record locator query doesn&apos;t return any value.</description>
        <inlineHelpText>This field records the creator that needs to be run when the record locator query doesn&apos;t return any value.</inlineHelpText>
        <label>Run SObject Creator On Record Not Found</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SObject_Creator__c</fullName>
        <description>This is the SObject creator for this column mapping</description>
        <inlineHelpText>This is the SObject creator for this column mapping</inlineHelpText>
        <label>SObject Creator</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SObject_Type__c</fullName>
        <description>This is the Target SObject type through the CSV upload process</description>
        <inlineHelpText>This is the Target SObject type through the CSV upload process. Valid values are (Grant_Award__c)</inlineHelpText>
        <label>SObject Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value_Parser__c</fullName>
        <description>This is the name of the class which will parse the value for this column.</description>
        <inlineHelpText>This is the name of the class which will parse the value for this column.</inlineHelpText>
        <label>Value Parser</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CSV Upload Mapping Column</label>
</CustomObject>

src/objects/Grant_Scheme__c.object
<CustomObject>
    <fields>
        <fullName>Allocation_Method__c</fullName>
        <description>Competed	- e.g. application based
Un-competed 	- e.g. where a charity writes to a Minister about an initiative they have and this aligns with the departmental objectives, so they get given a grant to make that initiative real
Formula 	- where the means by which the money is allocated is calculated through a formula
Criteria Based 	- where there is qualifying criteria in order to receive money, but as long as they qualify, the recipient gets the money, as there is no competition e.g. floods</description>
        <inlineHelpText>The method by which the grant was allocated. This can be either competed, formula, un-competed or criteria based. Definitions of each are given in the Data and System Glossary of Terms, found on the Home page.</inlineHelpText>
        <label>Scheme allocation method</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>General Grants - Competed</fullName>
                </value>
                <value>
                    <fullName>General Grants - Un-competed</fullName>
                </value>
                <value>
                    <fullName>General Grants - Criteria Based</fullName>
                </value>
                <value>
                    <fullName>Formula</fullName>
                </value>
                <value>
                    <fullName>Formula - Criteria Based</fullName>
                </value>
                <value>
                    <fullName>Grant in Aid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scheme_Reference_No__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is a reference number that can be given from a department&apos;s own internal system, should you wish to. It is optional &amp; will help reconciliation between GGIS &amp; your own system, but you don&apos;t have to include one.</inlineHelpText>
        <label>Scheme Reference No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Grant Scheme</label>
    <nameField>
        <displayFormat>SCH-{000000000}</displayFormat>
        <label>System Scheme Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CSVUploadMappingMockDataFactory.cls
public with sharing class CSVUploadMappingMockDataFactory {
	public List<CSV_Upload_Mapping_Column__c> create(){
		return new List<CSV_Upload_Mapping_Column__c>{
            // Recepient Mapping
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Organisation Name', Mapped_From_Field__c = 'Recipient Name', SObject_Type__c = Constant.SOBJECT_TYPE_ACCOUNT, Mapped_To_Field__c = 'Name', Required__c = true,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD_RECEPIENT,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Recepeint Address 1', Mapped_From_Field__c = 'Award Address 1', SObject_Type__c = Constant.SOBJECT_TYPE_ACCOUNT, Mapped_To_Field__c = 'Primary_Address_1__c',
                Required__c = true, CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD_RECEPIENT,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Recepeint Address 2', Mapped_From_Field__c = 'Award Address 2', SObject_Type__c = Constant.SOBJECT_TYPE_ACCOUNT, Mapped_To_Field__c = 'Primary_Address_2__c',
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD_RECEPIENT,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Recepeint City', Mapped_From_Field__c = 'Award City', SObject_Type__c = Constant.SOBJECT_TYPE_ACCOUNT, Mapped_To_Field__c = 'Primary_City__c',
                Required__c = true, CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD_RECEPIENT,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Recepeint County', Mapped_From_Field__c = 'Award County', SObject_Type__c = Constant.SOBJECT_TYPE_ACCOUNT, Mapped_To_Field__c = 'Primary_County__c',
                Required__c = false, CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD_RECEPIENT,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Recepeint Postal Code', Mapped_From_Field__c = 'Award Postal Code', SObject_Type__c = Constant.SOBJECT_TYPE_ACCOUNT, Mapped_To_Field__c = 'Primary_Postal_Code__c',
                Required__c = true, CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD_RECEPIENT,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Recepeint Country', Mapped_From_Field__c = 'Award Country', SObject_Type__c = Constant.SOBJECT_TYPE_ACCOUNT, Mapped_To_Field__c = 'Primary_Country__c',
                Required__c = true, CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD_RECEPIENT,
                Value_Parser__c = Constant.STRING_VALUE_PARSER_PICKLIST, Not_Found_Error_Message__c = 'Award Country contains an invalid value.',
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Recipient ID and Type', Mapped_From_Field__c = 'Recipient ID', SObject_Type__c = Constant.SOBJECT_TYPE_ACCOUNT, Mapped_To_Field__c = 'Recipient ID Type',
                Required__c = true, CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD_RECEPIENT,
                External_Id_Type_Column__c = true,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            // Award Mapping
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Award Recipient', Mapped_From_Field__c = 'Recipient ID', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Recipient ID Type', Required__c = true,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                External_Id_Type_Column__c = true, Query_Result_Id_Mapped_to_Field__c = 'Recipient__c',
                Record_Locator_Query__c = 'SELECT Id FROM Account WHERE ' + Constant.QUERY_INPUT_FIELD_TEMPLATE + ' = \'' + Constant.QUERY_INPUT_VALUE_TEMPLATE + '\' LIMIT 1',
                Run_SObject_Creator_On_Record_Not_Found__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD_RECEPIENT,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Grant Award Reference Number', Mapped_From_Field__c = 'Grant Award Reference Number', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Grant_Award_Reference_Number__c', 
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Grant Award Name', Mapped_From_Field__c = 'Grant Award Name', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Grant_Award_Name__c', Required__c = true,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Award Secondary Address 1', Mapped_From_Field__c = 'Award Address 1', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Recipient_Secondary_Address_1__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Award Secondary Address 2', Mapped_From_Field__c = 'Award Address 2', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Recipient_Secondary_Address_2__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Award Secondary City', Mapped_From_Field__c = 'Award City', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Recipient_Secondary_City__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Award Secondary County', Mapped_From_Field__c = 'Award County', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Recipient_Secondary_County__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Award Secondary Postal Code', Mapped_From_Field__c = 'Award Postal Code', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Recipient_Secondary_Postal_Code__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Award Secondary Country', Mapped_From_Field__c = 'Award Country', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Recipient_Secondary_Country__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                Value_Parser__c = Constant.STRING_VALUE_PARSER_PICKLIST, Not_Found_Error_Message__c = 'Award Country contains an invalid value.',
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Get exst organisation address', Mapped_From_Field__c = 'Get exisiting organisation address', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Get_existing_organisation_address__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                Value_Parser__c = Constant.STRING_VALUE_PARSER_BOOLEAN, CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Is GRNT Monitored', Mapped_From_Field__c = 'Is Grant Monitored', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Is_The_Grant_Monitored__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                Value_Parser__c = Constant.STRING_VALUE_PARSER_PICKLIST, Not_Found_Error_Message__c = 'Is Grant Monitored contains an invalid value.',
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Reason for no monitoring', Mapped_From_Field__c = 'Reason for no monitoring', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Reason_For_No_Monitoring__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Contact Forename', Mapped_From_Field__c = 'Contact Forename', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Contact_Forename__c', Required__c = true,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Contact Surname', Mapped_From_Field__c = 'Contact Surname', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Contact_Surname__c', Required__c = true,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Contact Email', Mapped_From_Field__c = 'Contact Email', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Contact_Email__c', Required__c = true,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Allocation Method', Mapped_From_Field__c = 'Allocation Method', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Allocation_Method__c', Required__c = true,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                Value_Parser__c = Constant.STRING_VALUE_PARSER_PICKLIST, Accept_Multi_Values__c = false, 
                Not_Found_Error_Message__c = 'Allocation Method contains an invalid value.',
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Grant Award Objective', Mapped_From_Field__c = 'Grant Award Objective', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Grant_Award_Objective__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Award Start Date', Mapped_From_Field__c = 'Award Start Date', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Award_Start_Date__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                Value_Parser__c = Constant.STRING_VALUE_PARSER_DATE,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Award End Date', Mapped_From_Field__c = 'Award End Date', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Award_End_Date__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                Value_Parser__c = Constant.STRING_VALUE_PARSER_DATE,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Total Amount funding agrmnt', Mapped_From_Field__c = 'Total Amount in funding agreement in GBP', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Total_Amount_in_funding_agreement__c', Required__c = true,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                Value_Parser__c = Constant.STRING_VALUE_PARSER_DECIMAL,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-' + TestDataFactory.TEST_CCOA_COLUMN, Mapped_From_Field__c = TestDataFactory.TEST_CCOA_COLUMN, 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'CCoA_L5__c', Required__c = true,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                Record_Locator_Query__c = 'SELECT Id FROM COA_L5__c WHERE Name = \'' + Constant.QUERY_INPUT_VALUE_TEMPLATE + '\' LIMIT 1',
                Not_Found_Error_Message__c = 'No ' + TestDataFactory.TEST_CCOA_COLUMN + ' was found with the provided Id.',
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Scheme Ref or SF Scheme Ref', Mapped_From_Field__c = Constant.GRANT_SCHEME_AND_SYSTEM_REFERENCE_LABEL, 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Grant_Scheme__c', Required__c = true,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD,
                Record_Locator_Query__c = 'SELECT Id FROM Grant_Scheme__c WHERE Name = \'' + Constant.QUERY_INPUT_VALUE_TEMPLATE + '\' OR Scheme_Reference_No__c = \'' + Constant.QUERY_INPUT_VALUE_TEMPLATE + '\' LIMIT 1',
                Not_Found_Error_Message__c = 'No Grant Scheme was found with the provided Id.',
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),

            //Intermediary Organisation 1
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Intermediary name 1', Mapped_From_Field__c = 'Intermediary name 1', SObject_Type__c = Constant.SOBJECT_TYPE_ACCOUNT, Mapped_To_Field__c = 'Name',
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD_INTERMEDIARY_ORGANISATION,
                Group__c = 1,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Intermediary 1 ID and Type', Mapped_From_Field__c = 'Intermediary Id 1', SObject_Type__c = Constant.SOBJECT_TYPE_ACCOUNT, Mapped_To_Field__c = 'Intermediary Id Type 1',
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD_INTERMEDIARY_ORGANISATION,
                External_Id_Type_Column__c = true, Group__c = 1,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),

            //Intermediary 1
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Intermediary Id 1', Mapped_From_Field__c = 'Intermediary Id 1', SObject_Type__c = Constant.SOBJECT_TYPE_INTERMEDIARY, Mapped_To_Field__c = 'Intermediary Id Type 1', 
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD_INTERMEDIARY,
                External_Id_Type_Column__c = true, Query_Result_Id_Mapped_to_Field__c = 'Intermediary_Organisation__c',
                Record_Locator_Query__c = 'SELECT Id FROM Account WHERE ' + Constant.QUERY_INPUT_FIELD_TEMPLATE + ' = \'' + Constant.QUERY_INPUT_VALUE_TEMPLATE + '\' LIMIT 1',
                Run_SObject_Creator_On_Record_Not_Found__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD_INTERMEDIARY_ORGANISATION,
                Group__c = 1,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Intermediary Role 1', Mapped_From_Field__c = 'Intermediary Role 1', SObject_Type__c = Constant.SOBJECT_TYPE_INTERMEDIARY, Mapped_To_Field__c = 'Role__c',
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD_INTERMEDIARY,
                Group__c = 1, Value_Parser__c = Constant.STRING_VALUE_PARSER_PICKLIST, Accept_Multi_Values__c = true, 
                Not_Found_Error_Message__c = 'Intermediary Role 1 contains an invalid value.',
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),

            //Intermediary Organisation 2
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Intermediary name 2', Mapped_From_Field__c = 'Intermediary name 2', SObject_Type__c = Constant.SOBJECT_TYPE_ACCOUNT, Mapped_To_Field__c = 'Name',
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD_INTERMEDIARY_ORGANISATION,
                Group__c = 2,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Intermediary 2 ID and Type', Mapped_From_Field__c = 'Intermediary Id 2', SObject_Type__c = Constant.SOBJECT_TYPE_ACCOUNT, Mapped_To_Field__c = 'Intermediary Id Type 2',
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD_INTERMEDIARY_ORGANISATION,
                External_Id_Type_Column__c = true, Group__c = 2,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            //Intermediary 2
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Intermediary Id 2', Mapped_From_Field__c = 'Intermediary Id 2', SObject_Type__c = Constant.SOBJECT_TYPE_INTERMEDIARY, Mapped_To_Field__c = 'Intermediary Id Type 2', 
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD_INTERMEDIARY,
                External_Id_Type_Column__c = true, Query_Result_Id_Mapped_to_Field__c = 'Intermediary_Organisation__c',
                Record_Locator_Query__c = 'SELECT Id FROM Account WHERE ' + Constant.QUERY_INPUT_FIELD_TEMPLATE + ' = \'' + Constant.QUERY_INPUT_VALUE_TEMPLATE + '\' LIMIT 1',
                Run_SObject_Creator_On_Record_Not_Found__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD_INTERMEDIARY_ORGANISATION,
                Group__c = 2,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-CRT-Intermediary Role 2', Mapped_From_Field__c = 'Intermediary Role 2', SObject_Type__c = Constant.SOBJECT_TYPE_INTERMEDIARY, Mapped_To_Field__c = 'Role__c',
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_CREATE_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_CREATOR_GRANT_AWARD_INTERMEDIARY,
                Group__c = 2, Value_Parser__c = Constant.STRING_VALUE_PARSER_PICKLIST, Accept_Multi_Values__c = true,
                Not_Found_Error_Message__c = 'Intermediary Role 2 contains an invalid value.',
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            // Award AMEND
            // Award Mapping
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-AMN-System Award Reference No', Mapped_From_Field__c = 'System Award Reference No', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Name', Read_Only__c = true,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_AMEND_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_AMEND_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-AMN-Grant Award Reference Number', Mapped_From_Field__c = 'Grant Award Reference Number', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Grant_Award_Reference_Number__c', 
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_AMEND_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_AMEND_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-AMN-Grant Award Name', Mapped_From_Field__c = 'Grant Award Name', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Grant_Award_Name__c', Required__c = true,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_AMEND_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_AMEND_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-AMN-Award Secondary Address 1', Mapped_From_Field__c = 'Award Address 1', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Recipient_Secondary_Address_1__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_AMEND_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_AMEND_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-AMN-Award Secondary Address 2', Mapped_From_Field__c = 'Award Address 2', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Recipient_Secondary_Address_2__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_AMEND_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_AMEND_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-AMN-Award Secondary City', Mapped_From_Field__c = 'Award City', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Recipient_Secondary_City__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_AMEND_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_AMEND_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-AMN-Award Secondary County', Mapped_From_Field__c = 'Award County', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Recipient_Secondary_County__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_AMEND_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_AMEND_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-AMN-Award Secondary Postal Code', Mapped_From_Field__c = 'Award Postal Code', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Recipient_Secondary_Postal_Code__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_AMEND_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_AMEND_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-AMN-Award Secondary Country', Mapped_From_Field__c = 'Award Country', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Recipient_Secondary_Country__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_AMEND_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_AMEND_GRANT_AWARD,
                Value_Parser__c = Constant.STRING_VALUE_PARSER_PICKLIST, Not_Found_Error_Message__c = 'Award Country contains an invalid value.',
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-AMN-Is GRNT Monitored', Mapped_From_Field__c = 'Is Grant Monitored', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Is_The_Grant_Monitored__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_AMEND_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_AMEND_GRANT_AWARD,
                Value_Parser__c = Constant.STRING_VALUE_PARSER_PICKLIST, Not_Found_Error_Message__c = 'Is Grant Monitored contains an invalid value.',
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-AMN-Reason for no monitoring', Mapped_From_Field__c = 'Reason for no monitoring', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Reason_For_No_Monitoring__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_AMEND_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_AMEND_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-AMN-Contact Forename', Mapped_From_Field__c = 'Contact Forename', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Contact_Forename__c', Required__c = true,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_AMEND_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_AMEND_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-AMN-Contact Surname', Mapped_From_Field__c = 'Contact Surname', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Contact_Surname__c', Required__c = true,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_AMEND_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_AMEND_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-AMN-Contact Email', Mapped_From_Field__c = 'Contact Email', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Contact_Email__c', Required__c = true,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_AMEND_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_AMEND_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-AMN-Allocation Method', Mapped_From_Field__c = 'Allocation Method', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Allocation_Method__c', Required__c = true,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_AMEND_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_AMEND_GRANT_AWARD,
                Value_Parser__c = Constant.STRING_VALUE_PARSER_PICKLIST, Accept_Multi_Values__c = false, 
                Not_Found_Error_Message__c = 'Allocation Method contains an invalid value.',
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-AMN-Grant Award Objective', Mapped_From_Field__c = 'Grant Award Objective', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Grant_Award_Objective__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_AMEND_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_AMEND_GRANT_AWARD,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-AMN-Award Start Date', Mapped_From_Field__c = 'Award Start Date', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Award_Start_Date__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_AMEND_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_AMEND_GRANT_AWARD,
                Value_Parser__c = Constant.STRING_VALUE_PARSER_DATE,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-AMN-Award End Date', Mapped_From_Field__c = 'Award End Date', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Award_End_Date__c', Required__c = false,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_AMEND_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_AMEND_GRANT_AWARD,
                Value_Parser__c = Constant.STRING_VALUE_PARSER_DATE,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-AMN-Total Amount funding agrmnt', Mapped_From_Field__c = 'Total Amount in funding agreement in GBP', 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'Total_Amount_in_funding_agreement__c', Required__c = true,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_AMEND_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_AMEND_GRANT_AWARD,
                Value_Parser__c = Constant.STRING_VALUE_PARSER_DECIMAL,
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            ),
            new CSV_Upload_Mapping_Column__c(
                Name = 'AWD-AMN-' + TestDataFactory.TEST_CCOA_COLUMN, Mapped_From_Field__c = TestDataFactory.TEST_CCOA_COLUMN, 
                SObject_Type__c = Constant.SOBJECT_TYPE_GRANT_AWARD, Mapped_To_Field__c = 'CCoA_L5__c', Required__c = true,
                CSV_Upload_Type__c = Constant.CSV_UPLOAD_AMEND_AWARD_TYPE, SObject_Creator__c = Constant.CSV_SOBJECT_AMEND_GRANT_AWARD,
                Record_Locator_Query__c = 'SELECT Id FROM COA_L5__c WHERE Name = \'' + Constant.QUERY_INPUT_VALUE_TEMPLATE + '\' LIMIT 1',
                Not_Found_Error_Message__c = 'No ' + TestDataFactory.TEST_CCOA_COLUMN + ' was found with the provided Id.',
                CSV_Upload_Recipient_Type__c = Constant.GRT_ORGANISATION
            )
        };
	}
}