src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Funder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Funder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Address_1__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The first line of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Address_2__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The second line of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_City__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The city of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Country__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The country of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Abu Dhabi</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Ajman</fullName>
                </value>
                <value>
                    <fullName>Akrotiri</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Ascension</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Baker Island</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>United Kingdom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_County__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The county of the address for an organisation. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Postal_Code__c</fullName>
        <description>Custom Address Fields are used because the Cabinet Office requires Data Solution to match Address 1, Address 2 pattern.</description>
        <inlineHelpText>The Location based data report is based on the accuracy of this postcode. This can be used every time an award is created for this Organisation. Each award can also have its own different address, separate to the one provided for an organisation.</inlineHelpText>
        <label>Primary Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Grant_Award__c.object
<CustomObject>
    <fields>
        <fullName>Allocation_Method__c</fullName>
        <inlineHelpText>The method by which the grant was allocated. This can be either competed, formula, un-competed or criteria based. Definitions of each are given in the Data and System Glossary of Terms, found on the Home page.</inlineHelpText>
        <label>Allocation Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>General Grants - Competed</fullName>
                </value>
                <value>
                    <fullName>General Grants - Un-competed</fullName>
                </value>
                <value>
                    <fullName>General Grants - Criteria Based</fullName>
                </value>
                <value>
                    <fullName>Formula</fullName>
                </value>
                <value>
                    <fullName>Grant in Aid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Award_End_Date__c</fullName>
        <inlineHelpText>The date the grant closes, as per grant award agreement or letter.</inlineHelpText>
        <label>Award End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Award_Start_Date__c</fullName>
        <inlineHelpText>The date the grant was issued, as per grant award agreement or letter.</inlineHelpText>
        <label>Award Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grant_Scheme__c</fullName>
        <description>This is the parent scheme for this award</description>
        <inlineHelpText>This is the System Scheme Reference No and clicking it will take you back to the Scheme that this award belong to.</inlineHelpText>
        <label>Grant Scheme</label>
        <referenceTo>Grant_Scheme__c</referenceTo>
        <relationshipLabel>Grant Awards</relationshipLabel>
        <relationshipName>Grant_Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Has_Postal_Code_Been_Checked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates if the postcode has been validated or not</description>
        <label>Has Postal Code Been Checked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Postal_Code_Valid__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates if the value for this post code is valid or not.</description>
        <inlineHelpText>This checkbox indicates if the value for this post code is valid or not.</inlineHelpText>
        <label>Is Postal Code Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Parliamentary_Constituency__c</fullName>
        <description>This value is generated automated based on the selected postcode.</description>
        <label>Postal Code Parliamentary Constituency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Region__c</fullName>
        <description>This value is generated automatically based on the selected postal code.</description>
        <label>Postal Code Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Amount_in_funding_agreement__c</fullName>
        <inlineHelpText>For Recipient Type: Organisation. The total amount in pounds of the grant award that was comitted in the grant award agreement.</inlineHelpText>
        <label>Total Amount in funding agreement in GBP</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Grant Award</label>
    <nameField>
        <displayFormat>GA-{000000}</displayFormat>
        <label>System Award Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Grant_Scheme__c.object
<CustomObject>
    <fields>
        <fullName>Allocation_Method__c</fullName>
        <description>Competed	- e.g. application based
Un-competed 	- e.g. where a charity writes to a Minister about an initiative they have and this aligns with the departmental objectives, so they get given a grant to make that initiative real
Formula 	- where the means by which the money is allocated is calculated through a formula
Criteria Based 	- where there is qualifying criteria in order to receive money, but as long as they qualify, the recipient gets the money, as there is no competition e.g. floods</description>
        <inlineHelpText>The method by which the grant was allocated. This can be either competed, formula, un-competed or criteria based. Definitions of each are given in the Data and System Glossary of Terms, found on the Home page.</inlineHelpText>
        <label>Scheme allocation method</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>General Grants - Competed</fullName>
                </value>
                <value>
                    <fullName>General Grants - Un-competed</fullName>
                </value>
                <value>
                    <fullName>General Grants - Criteria Based</fullName>
                </value>
                <value>
                    <fullName>Formula</fullName>
                </value>
                <value>
                    <fullName>Formula - Criteria Based</fullName>
                </value>
                <value>
                    <fullName>Grant in Aid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Funder__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the funder organisation lookup</description>
        <inlineHelpText>The entity that is funding the grant scheme (this is in most cases, a government department where the funds start)</inlineHelpText>
        <label>Funder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Is_Funder__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Grant Schemes (Funder)</relationshipLabel>
        <relationshipName>Grant_Schemes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Purpose__c</fullName>
        <description>details can be found on : https://docs.google.com/spreadsheets/d/1Hb7iIacx-Koy2lIrXoqSyzdTf0bh-1TRvCyR8Jwtif8/edit#gid=488764022</description>
        <inlineHelpText>The purpose that the grant is being paid out for. 5 mutually exclusive purposes have been identified. Definitions of each are given in the Data and System Glossary of Terms, found on the Home page. If no option suits, choose None of the above.</inlineHelpText>
        <label>Primary Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Supporting delivery of a public service</fullName>
                </value>
                <value>
                    <fullName>Supporting delivery of a public policy</fullName>
                </value>
                <value>
                    <fullName>Research &amp; Innovation</fullName>
                </value>
                <value>
                    <fullName>Financial Assistance / Support</fullName>
                </value>
                <value>
                    <fullName>Subscriptions and pension payments</fullName>
                </value>
                <value>
                    <fullName>None of the above</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant Scheme</label>
    <nameField>
        <displayFormat>SCH-{000000000}</displayFormat>
        <label>System Scheme Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Cabinet office backup/src/classes/AwardPostalCodeHeatMapControllerTest.cls
/******************************************************************************************
@Author         Hamed Izadpanah
@Date           19/02/2016
@Project        Cloud Sherpas Cabinet Office Data Source
@Description    This is the test unit for AwardPostalCodeHeatMapController
*******************************************************************************************/
@isTest
private class AwardPostalCodeHeatMapControllerTest{

	@testSetup()
    static void setupTestData(){
        TestDataFactory testFactory = new TestDataFactory();
        testFactory.insertReferenceData();
        Account department1 = testFactory.createAccount('Department1','NEW_CPID_Department1');
        department1.Primary_Address_1__c = 'Unit 1, Horse Guards Rd';
        department1.Primary_Address_2__c = 'HM Treasury';
        department1.Primary_City__c = 'London';
        department1.Primary_County__c = 'Greater London';
        department1.Primary_Country__c = 'United Kingdom';
        department1.Primary_Postal_Code__c = 'SW1A 2HQ';
        insert department1;
        User dept1SuperUser1 = testFactory.setupBasicUser(department1 ,'SuperUserContact1','Data Solution Portal - Super User');
        insert dept1SuperUser1;
        System.runAs(dept1SuperUser1){
            Grant_Scheme__c grantSchemeCreatedByDept1SuperUser1 = testFactory.createGrantScheme(
            	department1, 'Test Grant Award NonAdminRecord01', testFactory.testCOFOGLevel
            );
            insert grantSchemeCreatedByDept1SuperUser1;
            Grant_Award__c grantAwardCreatedByDept1SuperUser1 = testFactory.createGrantAward(
            	'Test Grant Award AdminRecord', department1, grantSchemeCreatedByDept1SuperUser1
            );
            grantAwardCreatedByDept1SuperUser1.Postal_Code_Geo_Location__Latitude__s = 51.503648907772100;
            grantAwardCreatedByDept1SuperUser1.Postal_Code_Geo_Location__Longitude__s = -0.126638914084856;
            grantAwardCreatedByDept1SuperUser1.Postal_Code_Region__c = 'London';
            grantAwardCreatedByDept1SuperUser1.Postal_Code_Parliamentary_Constituency__c = 'Islington North';
            grantAwardCreatedByDept1SuperUser1.Is_Postal_Code_Valid__c = true;
            grantAwardCreatedByDept1SuperUser1.Has_Postal_Code_Been_Checked__c = true;
            grantAwardCreatedByDept1SuperUser1.Total_Amount_in_funding_agreement__c = 100;
            Date startOfThisYearFY = Date.newInstance(Date.today().year(), 4, 1);
            grantAwardCreatedByDept1SuperUser1.Award_Start_Date__c = startOfThisYearFY.addMonths(-8);
            grantAwardCreatedByDept1SuperUser1.Award_End_Date__c = startOfThisYearFY.addMonths(-2);
            insert grantAwardCreatedByDept1SuperUser1;
        }
    }

	@isTest
	static void testGetAvailableRegions(){
		AwardPostalCodeHeatMapController controller = new AwardPostalCodeHeatMapController();
		controller.setNewMapCenter();
		List<SelectOption> availableRegions = controller.getAvailableRegions();
		System.assertEquals(2, availableRegions.size());
		System.assertEquals(Label.AwardPostalCodeHeatMapAllRegionsLabel, availableRegions[0].getLabel());
		System.assertEquals('', availableRegions[0].getValue());
		System.assertEquals('London', availableRegions[1].getLabel());
		System.assertEquals('London', availableRegions[1].getValue());
	}

	@isTest
	static void testGetAvailableConstituencies(){
		AwardPostalCodeHeatMapController controller = new AwardPostalCodeHeatMapController();
		List<SelectOption> availableConstituencies = controller.getAvailableConstituencies();
		System.assertEquals(2, availableConstituencies.size());
		System.assertEquals(Label.AwardPostalCodeHeatMapAllConstituenciesLabel, availableConstituencies[0].getLabel());
		System.assertEquals('', availableConstituencies[0].getValue());
		System.assertEquals('Islington North', availableConstituencies[1].getLabel());
		System.assertEquals('Islington North', availableConstituencies[1].getValue());
	}
	@isTest
	static void tetsGenerateQueryConditionsWithoutParams(){
		AwardPostalCodeHeatMapController controller = new AwardPostalCodeHeatMapController();
		controller.showActiveGrants = false;
		controller.filterGrantAward.Award_Start_Date__c = null;
		controller.filterGrantAward.Award_End_Date__c = null;
		controller.filterGrantAward.Postal_Code_Region__c = null;
		controller.filterGrantAward.Allocation_Method__c = null;
		String generatedQuery = controller.generateQueryConditions();
		System.assertEquals(false, generatedQuery.containsIgnoreCase('Award_Start_Date__c'));
		System.assertEquals(false, generatedQuery.containsIgnoreCase('Award_End_Date__c'));
		System.assertEquals(false, generatedQuery.containsIgnoreCase('Postal_Code_Region__c'));
		System.assertEquals(false, generatedQuery.containsIgnoreCase('Allocation_Method__c'));
		System.assertEquals(false, generatedQuery.containsIgnoreCase('Postal_Code_Parliamentary_Constituency__c'));
	}
	@isTest
	static void tetsGenerateQueryConditionsShowActiveGrants(){
		AwardPostalCodeHeatMapController controller = new AwardPostalCodeHeatMapController();
		controller.showActiveGrants = true;
		controller.filterGrantAward.Award_Start_Date__c = null;
		controller.filterGrantAward.Award_End_Date__c = null;
		controller.filterGrantAward.Postal_Code_Region__c = null;
		controller.filterGrantAward.Allocation_Method__c = null;
		String generatedQuery = controller.generateQueryConditions();
		System.assertEquals(true, generatedQuery.containsIgnoreCase('Award_Start_Date__c'));
		System.assertEquals(true, generatedQuery.containsIgnoreCase('Award_End_Date__c'));
	}
	@isTest
	static void tetsGenerateQueryConditionsWithStartDate(){
		AwardPostalCodeHeatMapController controller = new AwardPostalCodeHeatMapController();
		controller.showActiveGrants = false;
		controller.filterGrantAward.Award_Start_Date__c = Date.today();
		controller.filterGrantAward.Award_End_Date__c = null;
		controller.filterGrantAward.Postal_Code_Region__c = null;
		controller.filterGrantAward.Allocation_Method__c = null;
		String generatedQuery = controller.generateQueryConditions();
		System.assertEquals(true, generatedQuery.containsIgnoreCase('Award_Start_Date__c'));
		System.assertEquals(false, generatedQuery.containsIgnoreCase('Award_End_Date__c'));
	}
	@isTest
	static void tetsGenerateQueryConditionsWithEndDate(){
		AwardPostalCodeHeatMapController controller = new AwardPostalCodeHeatMapController();
		controller.showActiveGrants = false;
		controller.filterGrantAward.Award_Start_Date__c = null;
		controller.filterGrantAward.Award_End_Date__c = Date.today();
		controller.filterGrantAward.Postal_Code_Region__c = null;
		controller.filterGrantAward.Allocation_Method__c = null;
		String generatedQuery = controller.generateQueryConditions();
		System.assertEquals(false, generatedQuery.containsIgnoreCase('Award_Start_Date__c'));
		System.assertEquals(true, generatedQuery.containsIgnoreCase('Award_End_Date__c'));
	}
	@isTest
	static void tetsGenerateQueryConditionsWithRegion(){
		AwardPostalCodeHeatMapController controller = new AwardPostalCodeHeatMapController();
		controller.showActiveGrants = false;
		controller.filterGrantAward.Award_Start_Date__c = null;
		controller.filterGrantAward.Award_End_Date__c = null;
		controller.filterGrantAward.Postal_Code_Region__c = 'London';
		controller.filterGrantAward.Allocation_Method__c = null;
		String generatedQuery = controller.generateQueryConditions();
		System.assertEquals(true, generatedQuery.containsIgnoreCase('Postal_Code_Region__c'));
	}
	@isTest
	static void tetsGenerateQueryConditionsWithAwardAllocationMethod(){
		AwardPostalCodeHeatMapController controller = new AwardPostalCodeHeatMapController();
		controller.showActiveGrants = false;
		controller.filterGrantAward.Award_Start_Date__c = null;
		controller.filterGrantAward.Award_End_Date__c = null;
		controller.filterGrantAward.Postal_Code_Region__c = null;
		controller.filterGrantAward.Allocation_Method__c = 'Formula';
		String generatedQuery = controller.generateQueryConditions();
		System.assertEquals(true, generatedQuery.containsIgnoreCase('Allocation_Method__c'));
	}
	@isTest
	static void tetsGenerateQueryConditionsWithAwardConstituency(){
		AwardPostalCodeHeatMapController controller = new AwardPostalCodeHeatMapController();
		controller.showActiveGrants = false;
		controller.filterGrantAward.Award_Start_Date__c = null;
		controller.filterGrantAward.Award_End_Date__c = null;
		controller.filterGrantAward.Postal_Code_Region__c = null;
		controller.filterGrantAward.Allocation_Method__c = null;
		controller.filterGrantAward.Postal_Code_Parliamentary_Constituency__c = 'Bath';
		String generatedQuery = controller.generateQueryConditions();
		System.assertEquals(true, generatedQuery.containsIgnoreCase('Postal_Code_Parliamentary_Constituency__c'));
	}
	@isTest
	static void testGetHeatMapPoints(){
		AwardPostalCodeHeatMapController controller = new AwardPostalCodeHeatMapController();
		controller.showActiveGrants = false;
		controller.filterGrantAward.Award_Start_Date__c = null;
		controller.filterGrantAward.Award_End_Date__c = null;
		controller.filterGrantAward.Postal_Code_Region__c = 'London';
		controller.filterGrantAward.Allocation_Method__c = null;
		String heatMapPointsJSON = controller.getHeatMapPoints();
		String HEAT_MAP_JSON_RESPONSE = '[';
		HEAT_MAP_JSON_RESPONSE += 'new google.maps.LatLng(51.503648907772100,-0.126638914084856),';
		HEAT_MAP_JSON_RESPONSE += ']';
		System.assertEquals(HEAT_MAP_JSON_RESPONSE, heatMapPointsJSON);
	}
	@isTest
	static void testGetHeatMapPointsWithInvalidQuery(){
		AwardPostalCodeHeatMapController controller = new AwardPostalCodeHeatMapController();
		controller.showActiveGrants = false;
		controller.filterGrantAward.Award_Start_Date__c = null;
		controller.filterGrantAward.Award_End_Date__c = null;
		controller.filterGrantAward.Postal_Code_Region__c = 'London';
		controller.filterGrantAward.Allocation_Method__c = null;
		AwardPostalCodeHeatMapController.HEAT_MAP_BASE_QUERY_STRING += ' AND INVALID_FIELD = false'; 
		System.assertEquals(0, ApexPages.getMessages().size());
		String heatMapPointsJSON = controller.getHeatMapPoints();
		System.assertEquals(1, ApexPages.getMessages().size());
		System.assertEquals(ApexPages.Severity.ERROR, ApexPages.getMessages()[0].getSeverity());
		System.assertEquals(true, ApexPages.getMessages()[0].getDetail().containsIgnoreCase('No such column \'INVALID_FIELD\' on entity \'Grant_Award__c\''));
	}

	@isTest
	static void testGetLocationBasedSummary(){
		AwardPostalCodeHeatMapController controller = new AwardPostalCodeHeatMapController();
		controller.showActiveGrants = false;
		controller.filterGrantAward.Award_Start_Date__c = null;
		controller.filterGrantAward.Award_End_Date__c = null;
		controller.filterGrantAward.Postal_Code_Region__c = 'London';
		controller.filterGrantAward.Allocation_Method__c = null;
		controller.mapCurrentZoomRadius = 100;
		controller.mapCurrentCenterLat = 51.503648907772100;
		controller.mapCurrentCenterLong = -0.126638914084856;
		AggregateResult locationSummaryAgg = controller.getLocationBasedSummary();
		System.assertEquals(100, (Decimal) locationSummaryAgg.get('awardsAmount'));
		System.assertEquals(1, (Integer) locationSummaryAgg.get('awardsCount'));
	}
	@isTest
	static void testGetAllRegionTotalAmounts(){
		AwardPostalCodeHeatMapController controller = new AwardPostalCodeHeatMapController();
		controller.showActiveGrants = false;
		controller.filterGrantAward.Award_Start_Date__c = null;
		controller.filterGrantAward.Award_End_Date__c = null;
		controller.filterGrantAward.Postal_Code_Region__c = null;
		controller.filterGrantAward.Allocation_Method__c = null;
		controller.mapCurrentZoomRadius = 100;
		controller.mapCurrentCenterLat = 51.503648907772100;
		controller.mapCurrentCenterLong = -0.126638914084856;
		List<AggregateResult> locationSummaryAggs = controller.getAllRegionTotalAmounts();
		System.assertEquals(1, locationSummaryAggs.size());
		System.assertEquals('London', (String) locationSummaryAggs[0].get('Postal_Code_Region__c'));
		System.assertEquals(100, (Decimal) locationSummaryAggs[0].get('awardsAmount'));
	}

	@isTest
	static void testGetAllRegionTotalSchemeFunder(){
		Id accountId = [
			SELECT Id  
			FROM Account
		].Id;
		AwardPostalCodeHeatMapController controller = new AwardPostalCodeHeatMapController();
		controller.showActiveGrants = false;
		controller.filterGrantScheme.Funder__c = accountId;
		controller.mapCurrentZoomRadius = 100;
		controller.mapCurrentCenterLat = 51.503648907772100;
		controller.mapCurrentCenterLong = -0.126638914084856;
		List<AggregateResult> locationSummaryAggs = controller.getAllRegionTotalAmounts();
		System.assertEquals(1, locationSummaryAggs.size());
		System.assertEquals('London', (String) locationSummaryAggs[0].get('Postal_Code_Region__c'));
		System.assertEquals(100, (Decimal) locationSummaryAggs[0].get('awardsAmount'));
	}

	@isTest
	static void testGetAllRegionTotalSchemePrimaryPurpose(){
		AwardPostalCodeHeatMapController controller = new AwardPostalCodeHeatMapController();
		controller.showActiveGrants = false;
		controller.filterGrantScheme.Primary_Purpose__c = 'Supporting delivery of a public service';
		controller.mapCurrentZoomRadius = 100;
		controller.mapCurrentCenterLat = 51.503648907772100;
		controller.mapCurrentCenterLong = -0.126638914084856;
		List<AggregateResult> locationSummaryAggs = controller.getAllRegionTotalAmounts();
		System.assertEquals(1, locationSummaryAggs.size());
		System.assertEquals('London', (String) locationSummaryAggs[0].get('Postal_Code_Region__c'));
		System.assertEquals(100, (Decimal) locationSummaryAggs[0].get('awardsAmount'));
	}

	@isTest
	static void testGetAllRegionTotalSchemeRecipientSector(){
		AwardPostalCodeHeatMapController controller = new AwardPostalCodeHeatMapController();
		controller.showActiveGrants = false;
		controller.filterGrantScheme.Recipient_Sector__c = 'Local Government';
		controller.mapCurrentZoomRadius = 100;
		controller.mapCurrentCenterLat = 51.503648907772100;
		controller.mapCurrentCenterLong = -0.126638914084856;
		List<AggregateResult> locationSummaryAggs = controller.getAllRegionTotalAmounts();
		System.assertEquals(1, locationSummaryAggs.size());
		System.assertEquals('London', (String) locationSummaryAggs[0].get('Postal_Code_Region__c'));
		System.assertEquals(100, (Decimal) locationSummaryAggs[0].get('awardsAmount'));
	}
}