src/objects/Bypass__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting allows users to bypass functionalities - E.G: Triggers, Validation Rules, Workflow rules and etc...</description>
    <fields>
        <fullName>Grant_Reminders__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag should be checked to turn off the Grant Reminder functionality. By default this will be unchecked (i.e, Grant Reminders will be sent).</description>
        <inlineHelpText>This flag should be checked to turn off the Grant Reminder functionality. By default this will be unchecked (i.e, Grant Reminders will be sent).</inlineHelpText>
        <label>Grant Reminders</label>
        <type>Checkbox</type>
    </fields>
    <label>Bypass</label>
</CustomObject>

src/objects/Grant_Award__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Payment__c</fullName>
        <inlineHelpText>The actual payment amount that has been given to the Recipient(s). This is to be filled in only as a total amount, once the last payment has been made, as one activity.</inlineHelpText>
        <label>Actual Payment</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Award_End_Date__c</fullName>
        <inlineHelpText>The date the grant closes, as per grant award agreement or letter.</inlineHelpText>
        <label>Award End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Award_Start_Date__c</fullName>
        <inlineHelpText>The date the grant was issued, as per grant award agreement or letter.</inlineHelpText>
        <label>Award Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Frequency__c</fullName>
        <inlineHelpText>When the payments are made to recipients. Upfront/ End = Payments are made at beginning/ end of grant lifecycle. Instalment payments are made at regular intervals throughout grant lifecycle. Ad-hoc payments are at irregular times.</inlineHelpText>
        <label>Payment Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ad-hoc payments</fullName>
                </value>
                <value>
                    <fullName>Upfront payments</fullName>
                </value>
                <value>
                    <fullName>End payments</fullName>
                </value>
                <value>
                    <fullName>Instalment payments</fullName>
                </value>
                <value>
                    <fullName>Milestone payments</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant Award</label>
    <nameField>
        <displayFormat>GA-{000000}</displayFormat>
        <label>System Award Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>SendGrantReminder__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag is used to trigger a workflow which sends the &apos;Incomplete Grants&apos; monthly email to the related user. The flag is checked by a scheduled apex job based on business rules.</description>
        <label>Send Incomplete Grant Reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SendInactiveUserEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This flag is used to send reminder email to Admin user notifying the list of Inactive users with Grants</inlineHelpText>
        <label>Send Inactive User Email</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SendIncompleteGrantReminder.cls
/******************************************************************************************
@Author         Bhushan Sukumar
@Date           29 Mar 2016
@Description    This is the batch processor which updates the 'Send Grant Reminder' flag on users
*******************************************************************************************/
global class SendIncompleteGrantReminder
    implements Database.Batchable<sObject>, Database.AllowsCallouts, Schedulable {

    global String query {get; set;}

    global Database.QueryLocator start(Database.BatchableContext BC) {

        return Database.getQueryLocator([SELECT Id,
                                         CreatedById, Actual_Payment__c
                                         , Payment_Frequency__c
                                         , Award_Start_Date__c
                                         , Award_End_Date__c
                                         , CreatedBy.IsActive
                                         FROM Grant_Award__c
                                         WHERE Actual_Payment__c = null
                                                 AND ((Payment_Frequency__c = : Constant.UPFRONT_PAYMENT
                                                         AND Award_Start_Date__c = LAST_MONTH)
                                                         OR ((Payment_Frequency__c = : Constant.INSTALMENT_PAYMENTS
                                                                 OR Payment_Frequency__c = : Constant.END_PAYMENT
                                                                         OR Payment_Frequency__c = : Constant.ADHOC_PAYMENT)
                                                                 AND Award_End_Date__c = LAST_MONTH))]);
    }

    global void execute(SchedulableContext sc) {
        Database.executeBatch(new SendIncompleteGrantReminder());
    }

    global void execute(Database.BatchableContext BC, List<Grant_Award__c> grantAwards) {
        //Checking the 'Bypass' switch before executing the logic.
        Bypass__c bypassSetting = Bypass__c.getInstance();
        //flag the determine if any of the 'CreatedBy' user is inactive.
        boolean notifyAdmin = false;
        if (!bypassSetting.Grant_Reminders__c) {
            Set<Id> userIds = new Set<Id>();
            for (Grant_Award__c gAward : grantAwards) {
                if (!userIds.contains(gAward.createdById) && gAward.CreatedBy.IsActive) {
                    userIds.add(gAward.CreatedById);
                }
                if (!gAward.CreatedBy.IsActive) {
                    notifyAdmin = true;
                }
            }
            List<User> usersToUpdate = [SELECT Id,
                                        SendGrantReminder__c FROM User
                                        WHERE Id IN : userIds LIMIT 10000];
            for (User userToRemind : usersToUpdate) {
                userToRemind.SendGrantReminder__c = true;
            }
            update usersToUpdate;
            if (notifyAdmin) {
                List<User> adminUsers = [SELECT Id,
                                         SendInactiveUserEmail__c
                                         FROM User
                                         WHERE Profile.Name = : Constant.PROFILE_SYSADMIN
                                                 AND IsActive = TRUE LIMIT 10000];
                for (User admin : adminUsers) {
                    //checking this flag will trigger the workflow to send email
                    admin.SendInactiveUserEmail__c = true;
                }
                update adminUsers;
            }
        }
    }

    global void finish(Database.BatchableContext BC) {

    }
}