src/objects/CSV_Upload__c.object
<CustomObject>
    <description>This is the object that saves the CSV upload attempts by super users.</description>
    <fields>
        <fullName>Apex_Batch_Id__c</fullName>
        <description>This is the Salesforce ID for the corresponding batch job for this upload attempt.</description>
        <externalId>true</externalId>
        <label>Apex Batch Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Processing_Status__c</fullName>
        <description>This is the batch status for this CSV upload item.</description>
        <label>Processing Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Queued</fullName>
                </value>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Finished</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Records_Created_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total number of records inserted in by this csv upload process.</description>
        <inlineHelpText>Total number of records inserted in by this csv upload process.</inlineHelpText>
        <label>Records Created Count</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Records_Updated_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Total number of records updated in by this csv upload process.</description>
        <inlineHelpText>Total number of records updated in by this csv upload process.</inlineHelpText>
        <label>Records Updated Count</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Records_Failed__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the total number of records failed the upload process.</description>
        <label>Total Records Failed</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This is the process type for this data upload.</description>
        <inlineHelpText>This is the process type for this data upload.</inlineHelpText>
        <label>Type</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Data Upload</label>
    <nameField>
        <displayFormat>CSVU-{0000000}</displayFormat>
        <label>FileUpload Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Uploads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Grant_Award__c.object
<CustomObject>
    <label>Grant Award</label>
    <nameField>
        <displayFormat>GA-{000000}</displayFormat>
        <label>System Award Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CSVUploadProcessor.cls
/******************************************************************************************
@Author         Hamed Izadpanah
@Date           03/10/2015
@Project        Cloud Sherpas Cabinet Office Data Source
@Description    This is a batch processor which is used to process a large number of CSV rows
*******************************************************************************************/
public with sharing class CSVUploadProcessor implements Database.Batchable<CSVDocument.CSVRow>, Database.Stateful{

	private CSVDocument documentToUpload;
	
	private List<CSVDocument.CSVRow> rowsWithError = new List<CSVDocument.CSVRow>();

	CSVUploadSObjectFactory sobjectFactory; 
	public CSVUploadProcessor(CSVDocument documentToUpload, CSVUploadSObjectFactory sobjectFactory) {
		this.documentToUpload = documentToUpload;
		this.sobjectFactory = sobjectFactory;
	}

	public Iterable<CSVDocument.CSVRow> start(Database.BatchableContext bc) {
		CSV_Upload__c csvUploadToUpsert = new CSV_Upload__c(
			Processing_Status__c = Constant.CSV_UPLOAD_PT_STARTED,
			Type__c = sobjectFactory.getType(),
			Apex_Batch_Id__c = Id.valueOf(bc.getJobId())
		);
		upsert csvUploadToUpsert Apex_Batch_Id__c;
		return documentToUpload.allRows;
	} 

	public void execute(Database.BatchableContext bc, List<CSVDocument.CSVRow> csvRows){
		List<Grant_Award__c> grantAwardsToInsert = new List<Grant_Award__c>();
		Integer failedRecordsCount = 0;
		//CSVUploadSObjectFactory sobjectFactory = mapping.getSObjectFactory();
		for(CSVDocument.CSVRow rowToHandle : csvRows){
			List<String> errorMessages = new List<String>();
			SavePoint sp = Database.setSavePoint();
			try{
				sobjectFactory.build(rowToHandle);
			} catch (DmlException exceptionToHanlde){
				for(Integer i = 0; i < exceptionToHanlde.getNumDml(); i++){
					errorMessages.add(exceptionToHanlde.getDmlMessage(i));
				}
			} catch(Exception exceptionToHandle){
				errorMessages.add(exceptionToHandle.getMessage());
			}
			if(!errorMessages.isEmpty()){
				failedRecordsCount++;
				while(rowToHandle.columnValues.size() < rowToHandle.columnNames.size()){
					rowToHandle.columnValues.add(null);
				}
				String errorMessageToAdd = String.join(errorMessages, '; ');
				rowToHandle.columnValues.add(errorMessageToAdd);
				rowsWithError.add(rowToHandle);
				Database.rollBack(sp);
			}
		}
		List<CSV_Upload__c> foundRelatedCSVUploads = [
			SELECT Id, Records_Created_Count__c, Records_Updated_Count__c, Total_Records_Failed__c 
			FROM CSV_Upload__c WHERE Apex_Batch_Id__c = :Id.valueOf(bc.getJobId())
			LIMIT 1
		];
		if(!foundRelatedCSVUploads.isEmpty()){
			CSV_Upload__c csvUploadToChange = foundRelatedCSVUploads[0];
			sobjectFactory.addOperationsCountDetails(csvUploadToChange);
			csvUploadToChange.Total_Records_Failed__c = csvUploadToChange.Total_Records_Failed__c + failedRecordsCount;
			csvUploadToChange.Processing_Status__c = Constant.CSV_UPLOAD_PT_IN_PROGRESS;
			update csvUploadToChange;
		}
	}

	public void finish(Database.BatchableContext bc){
		CSV_Upload__c csvUploadToUpsert = new CSV_Upload__c(
			Processing_Status__c = Constant.CSV_UPLOAD_PT_FINISHED,
			Apex_Batch_Id__c = Id.valueOf(bc.getJobId())
		);
		upsert csvUploadToUpsert Apex_Batch_Id__c;
		if(!rowsWithError.isEmpty()){
			List<String> csvColumnNames = rowsWithError[0].columnNames;
			csvColumnNames.add('Error Details');
			CSVDocument errorCSVDocument = new CSVDocument(csvColumnNames, rowsWithError);
			insert new Attachment(
				Name = 'error-file.csv',
				Body = Blob.valueOf(errorCSVDocument.convertToString()),
				ParentId = csvUploadToUpsert.Id
			);
		}
	}
}