src/objects/CSV_Upload_Mapping_Column__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is the CSV Upload mapping for the CSV upload functionality.</description>
    <fields>
        <fullName>Accept_Multi_Values__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This value shows if the target mapped to field is a multi picklist value or a single picklist vlaue</description>
        <inlineHelpText>This value shows if the target mapped to field is a multi picklist value or a single picklist vlaue</inlineHelpText>
        <label>Accept Multi Values</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mapped_To_Field__c</fullName>
        <description>This is the From to in the CSV file. This value needs to be exactly the same as it is on the Target Object</description>
        <inlineHelpText>This is the From to in the CSV file. This value needs to be exactly the same as it is on the Target Object</inlineHelpText>
        <label>Mapped To Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Not_Found_Error_Message__c</fullName>
        <description>This error message is shown when the Record Locator Query doesn&apos;t return any records.</description>
        <inlineHelpText>This error message is shown when the Record Locator Query doesn&apos;t return any records.</inlineHelpText>
        <label>Not Found Error Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SObject_Type__c</fullName>
        <description>This is the Target SObject type through the CSV upload process</description>
        <inlineHelpText>This is the Target SObject type through the CSV upload process. Valid values are (Grant_Award__c)</inlineHelpText>
        <label>SObject Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CSV Upload Mapping Column</label>
</CustomObject>

Cabinet office backup/src/classes/StringValueParser.cls
/******************************************************************************************
@Author         Hamed Izadpanah
@Date           03/10/2015
@Project        Cloud Sherpas Cabinet Office Data Source
@Description    This class parses string values into different types. This is used for CSV Upload process
*******************************************************************************************/
public abstract with sharing class StringValueParser {

	protected CSV_Upload_Mapping_Column__c targetMappingSetting;

	public void setTargetMappingSetting(CSV_Upload_Mapping_Column__c targetMappingSetting){
		this.targetMappingSetting = targetMappingSetting;
	}
	public abstract Object parse(String valueToParse);

	public class StringToDate extends StringValueParser{
		public override Object parse(String valueToParse){
			Date returnValue = String.isNotBlank(valueToParse) ? Date.parse(valueToParse) : null;
			return returnValue;
		}
	}
	public class StringToDecimal extends StringValueParser{
		public override Object parse(String valueToParse){
			Decimal returnValue = String.isNotBlank(valueToParse) ? Decimal.valueOf(valueToParse.replaceAll(',', '')) : null;
			return returnValue;
		}
	}
	public class StringToBoolean extends StringValueParser{
		public override Object parse(String valueToParse){
			Boolean returnValue = false;
			Set<String> TRUE_VALUES = new Set<String>{
				'YES',
				'Y',
				'TRUE',
				'1'
			};
			if(String.isNotBlank(valueToParse) && TRUE_VALUES.contains(valueToParse.trim().toUpperCase())){
				returnValue = true;
			}
			return returnValue;
		}
	}
	public class StringToPicklistValues extends StringValueParser{
		public override Object parse(String valueToParse){
			String returnValue = null;
			List<String> validatedValues = new List<String>();
			DescribeSObjectResult sObjectDescribeToCheck = Schema.getGlobalDescribe().get(targetMappingSetting.SObject_Type__c).getDescribe();
			List<Schema.PicklistEntry> availablePicklistOptions = sObjectDescribeToCheck.fields.getMap().get(targetMappingSetting.Mapped_To_Field__c).getDescribe().getPicklistValues();
			for(Schema.PicklistEntry availablePicklistOption : availablePicklistOptions){
				String picklistValue = availablePicklistOption.getValue();
				if(valueToParse.containsIgnoreCase(picklistValue)){
					validatedValues.add(picklistValue);
					if(!targetMappingSetting.Accept_Multi_Values__c){
						break;
					}
				}
			}
			if(String.isNotBlank(valueToParse) && validatedValues.isEmpty()){
				throw new InvalidInputException(targetMappingSetting.Not_Found_Error_Message__c);
			}
			returnValue = String.join(validatedValues,';');
			return returnValue;
		}
	}

	public class InvalidInputException extends Exception{}
}