src/objects/Grant_Scheme__c.object
<CustomObject>
    <fields>
        <fullName>Intermediated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field indicates if the Grant Scheme has been intermediated through intermediary organisations. This is used when the use know that the Grant Scheme has been intermediated but doesn&apos;t have enough information about the intermediary organisation to create the connection.</description>
        <inlineHelpText>This field is asking if the grant scheme will be run with the help of an intermediary or not. Even if you don&apos;t know who the intermediary will be, you can add it to the scheme later, but you should know if it&apos;s going to be intermediated or not.</inlineHelpText>
        <label>Intermediated</label>
        <type>Checkbox</type>
    </fields>
    <label>Grant Scheme</label>
    <nameField>
        <displayFormat>SCH-{000000000}</displayFormat>
        <label>System Scheme Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Cabinet office backup/src/classes/GrantSchemePrivilegeBannerExtTest.cls
/******************************************************************************************
@Author         Bhushan Sukumar
@Date           22 Mar 2016
@Project        Cloud Sherpas Cabinet Office Data Source
@Description    Test class for unit testing GrantSchemePrivilegeBannerExt
*******************************************************************************************/
@isTest
private class GrantSchemePrivilegeBannerExtTest {

    @testSetup
    static void setupTestData() {
        TestDataFactory testFactory = new TestDataFactory();
        testFactory.insertReferenceData();
        Account funderAccount = testFactory.createAccount('New Funder', 'FUN123');
        Account testDepartment = testFactory.createAccount('My New Department', 'DEP123');

        insert funderAccount;
        insert testDepartment;

        Grant_Scheme__c gScheme = testFactory.createGrantScheme(funderAccount, 'Test Grant Scheme', testFactory.testCOFOGLevel);
        gScheme.Intermediated__c = true;
        insert gScheme;
    }

    @isTest
    static void testInitialise() {
        List<Grant_Scheme__c> gSchemes = [SELECT Id FROM Grant_Scheme__c];
        Test.startTest();
            ApexPages.StandardController stdCont = new ApexPages.StandardController(gSchemes[0]);
            GrantSchemePrivilegeBannerExt bannerExt = new GrantSchemePrivilegeBannerExt(stdCont);
        Test.stopTest();
        System.assertEquals(0, bannerExt.getCountOfRelatedIntermediaries());
    }
}