src/objects/Grant_Award__c.object
<CustomObject>
    <fields>
        <fullName>Has_Postal_Code_Been_Checked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates if the postcode has been validated or not</description>
        <label>Has Postal Code Been Checked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Postal_Code_Valid__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates if the value for this post code is valid or not.</description>
        <inlineHelpText>This checkbox indicates if the value for this post code is valid or not.</inlineHelpText>
        <label>Is Postal Code Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Admin_County__c</fullName>
        <description>This is the the admin county value received from the webservice call out.</description>
        <label>Postal Code Admin County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Admin_Ward__c</fullName>
        <description>This is the ward value received from the postal code webservice callout.</description>
        <label>Postal Code Admin Ward</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_CCG__c</fullName>
        <description>This is the Clinical Commissioning Group value received from the webservice call out.</description>
        <label>Postal Code CCG</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Country__c</fullName>
        <description>This is the country value received from the web service call out.</description>
        <label>Postal Code Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_European_Electoral_Region__c</fullName>
        <description>This is the electoral region received from postal code webservice call out.</description>
        <label>Postal Code European Electoral Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Incode__c</fullName>
        <description>The incode value for the postal code received from the webservice call out.</description>
        <label>Postal Code Incode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_NHS_Health_Authority__c</fullName>
        <description>This is the health authority received from the webservice call out.</description>
        <label>Postal Code NHS Health Authority</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_NUTS__c</fullName>
        <description>Nomenclature of Units for Territorial Statistics (NUTS) / Local Administrative Units (LAU) areas received from the webservice callout.</description>
        <label>Postal Code NUTS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Outcode__c</fullName>
        <description>This is the outcode for postal code received from webservice call out.</description>
        <label>Postal Code Outcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Parish__c</fullName>
        <description>This is the parish value for postal code webservice call out.</description>
        <label>Postal Code Parish</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Parliamentary_Constituency__c</fullName>
        <description>This value is generated automated based on the selected postcode.</description>
        <label>Postal Code Parliamentary Constituency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Primary_Care_Trust__c</fullName>
        <description>This is the primary care trust value received from the webservice call out.</description>
        <label>Postal Code Primary Care Trust</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Region__c</fullName>
        <description>This value is generated automatically based on the selected postal code.</description>
        <label>Postal Code Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Validation_Error_Message__c</fullName>
        <description>These is the error message returned from the post code validation error.</description>
        <inlineHelpText>These is the error message returned from the post code validation error.</inlineHelpText>
        <label>Postal Code Validation Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Recipient_Secondary_Postal_Code__c</fullName>
        <inlineHelpText>The Location based data report is based on the accuracy of this postcode. If a grant award is going to a different address than the one already stored for the Recipient Organisation, then populate the postcode of the organisation&apos;s address.</inlineHelpText>
        <label>Recipient Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Grant Award</label>
    <nameField>
        <displayFormat>GA-{000000}</displayFormat>
        <label>System Award Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Cabinet office backup/src/classes/GrantAwardPostalCodeValidator.cls
/******************************************************************************************
@Author         Hamed Izadpanah
@Date           18/02/2016
@Project        Cloud Sherpas Cabinet Office Data Source
@Description    This is the batch processor which validates the post codes value on the Grnat Award
*******************************************************************************************/
public class GrantAwardPostalCodeValidator implements Database.Batchable<sObject>, Database.AllowsCallouts, Schedulable {
	
	public Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator([
			SELECT Id, Recipient_Secondary_Postal_Code__c
			FROM Grant_Award__c
			WHERE Recipient_Secondary_Postal_Code__c != null
			AND Has_Postal_Code_Been_Checked__c = false
		]);
	}

	public void execute(SchedulableContext sc){
		Database.executeBatch(this, 10);
	}

   	public void execute(Database.BatchableContext BC, List<Grant_Award__c> grantAwards) {
		PostCodesIO postCodesIOInstance = new PostCodesIO();
		for(Grant_Award__c grantAwardToValidate : grantAwards){
			grantAwardToValidate.Is_Postal_Code_Valid__c = false;
			try{
				PostCodesIO.PostCodeResult postCodeDetails;
				if(Test.isRunningTest()){
					postCodeDetails = PostCodesIO.generateMockResult();
				} else {
					postCodeDetails = postCodesIOInstance.retrievePostCodeDetails(grantAwardToValidate.Recipient_Secondary_Postal_Code__c);
				}
				grantAwardToValidate.Recipient_Secondary_Postal_Code__c = postCodeDetails.postcode;
				grantAwardToValidate.Postal_Code_Region__c = postCodeDetails.region;
				grantAwardToValidate.Postal_Code_Geo_Location__Latitude__s = postCodeDetails.latitude;
				grantAwardToValidate.Postal_Code_Geo_Location__Longitude__s = postCodeDetails.longitude;
				grantAwardToValidate.Postal_Code_Parliamentary_Constituency__c = postCodeDetails.parliamentary_constituency;
				grantAwardToValidate.Postal_Code_Country__c = postCodeDetails.country;
				grantAwardToValidate.Postal_Code_European_Electoral_Region__c = postCodeDetails.european_electoral_region;
				grantAwardToValidate.Postal_Code_NHS_Health_Authority__c = postCodeDetails.nhs_ha;
				grantAwardToValidate.Postal_Code_Primary_Care_Trust__c = postCodeDetails.primary_care_trust;
				grantAwardToValidate.Postal_Code_CCG__c = postCodeDetails.ccg;
				grantAwardToValidate.Postal_Code_NUTS__c = postCodeDetails.nuts;
				grantAwardToValidate.Postal_Code_Admin_County__c = postCodeDetails.admin_county;
				grantAwardToValidate.Postal_Code_Admin_Ward__c = postCodeDetails.admin_ward;
				grantAwardToValidate.Postal_Code_Parish__c = postCodeDetails.parish;
				grantAwardToValidate.Postal_Code_Incode__c = postCodeDetails.incode;
				grantAwardToValidate.Postal_Code_Outcode__c = postCodeDetails.outcode;
				grantAwardToValidate.Is_Postal_Code_Valid__c = true;
			} catch(PostCodesIO.PostCodeNotFoundException postalCodeNotFoundException){
				grantAwardToValidate.Postal_Code_Validation_Error_Message__c = postalCodeNotFoundException.getMessage();
				grantAwardToValidate.Is_Postal_Code_Valid__c = false;
			} catch(Exception genericException){
				grantAwardToValidate.Postal_Code_Validation_Error_Message__c = 'System Error: ' + genericException.getMessage() + ' \n Stack Trace: ' + genericException.getStackTraceString();
				grantAwardToValidate.Is_Postal_Code_Valid__c = false;
			}
			grantAwardToValidate.Has_Postal_Code_Been_Checked__c = true;
		}
		update grantAwards;
	}
	
	public void finish(Database.BatchableContext BC) {
		
	}
	
}