src/objects/Grant_Scheme__c.object
<CustomObject>
    <label>Grant Scheme</label>
    <nameField>
        <displayFormat>SCH-{000000000}</displayFormat>
        <label>System Scheme Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Intermediary__c.object
<CustomObject>
    <description>This is the organisation which carries out the intermediary role</description>
    <fields>
        <fullName>Grant_Scheme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the related grant scheme</description>
        <label>System Scheme Reference No</label>
        <referenceTo>Grant_Scheme__c</referenceTo>
        <relationshipLabel>Intermediaries</relationshipLabel>
        <relationshipName>Intermediaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Intermediary</label>
    <nameField>
        <displayFormat>INT-{00000000}</displayFormat>
        <label>Intermediary Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intermediaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CabinetOffice/src/classes/GrantSchemePrivilegeBannerExt.cls
/******************************************************************************************
@Author         Bhushan Sukumar
@Date           21 Mar 2016
@Project        Cloud Sherpas Cabinet Office Data Source
@Description    This is an extension class for the GrantSchemePrivilegeBanner VF banner. The
rendering logic of the warning messages are handled in this class
*******************************************************************************************/
public with sharing class GrantSchemePrivilegeBannerExt {
    private final ApexPages.StandardController stdCon;
    
    public GrantSchemePrivilegeBannerExt(ApexPages.StandardController stdCon) {
        this.stdCon = stdCon;
    }

    public Integer getCountOfRelatedIntermediaries() {
        return [
            SELECT COUNT()
            FROM Intermediary__c
            WHERE Grant_Scheme__c = :stdCon.getId()
            LIMIT 1
        ];
    }
}