src/objects/Grant_Award__c.object
<CustomObject>
    <fields>
        <fullName>Grant_Scheme__c</fullName>
        <description>This is the parent scheme for this award</description>
        <inlineHelpText>This is the System Scheme Reference No and clicking it will take you back to the Scheme that this award belong to.</inlineHelpText>
        <label>Grant Scheme</label>
        <referenceTo>Grant_Scheme__c</referenceTo>
        <relationshipLabel>Grant Awards</relationshipLabel>
        <relationshipName>Grant_Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Portal_User_Cannot_Delete_This_Record__c</fullName>
        <formula>AND( 
NOT($Setup.Bypass__c.Validation_Rules__c) 
, NOT($Setup.Bypass__c.Business_Rules_for_Edit_and_Delete__c) 
, OR($Profile.Name = &apos;Data Solution Portal - Centre User&apos;, $Profile.Name = &apos;Data Solution Portal - User&apos;) 
)</formula>
        <label>Portal User Cannot Delete This Record</label>
        <type>Checkbox</type>
    </fields>
    <label>Grant Award</label>
    <nameField>
        <displayFormat>GA-{000000}</displayFormat>
        <label>System Award Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Grant_Scheme__c.object
<CustomObject>
    <fields>
        <fullName>Portal_User_Cannot_Delete_This_Record__c</fullName>
        <formula>AND( 
NOT($Setup.Bypass__c.Validation_Rules__c) 
, NOT($Setup.Bypass__c.Business_Rules_for_Edit_and_Delete__c) 
, OR($Profile.Name = &apos;Data Solution Portal - Centre User&apos;, $Profile.Name = &apos;Data Solution Portal - User&apos;)
)</formula>
        <label>Portal User Cannot Delete This Record</label>
        <type>Checkbox</type>
    </fields>
    <label>Grant Scheme</label>
    <nameField>
        <displayFormat>SCH-{000000000}</displayFormat>
        <label>System Scheme Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Intermediary__c.object
<CustomObject>
    <description>This is the organisation which carries out the intermediary role</description>
    <fields>
        <fullName>Grant_Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the related grant award for this intermediary record</description>
        <label>System Award Reference No</label>
        <referenceTo>Grant_Award__c</referenceTo>
        <relationshipLabel>Intermediaries</relationshipLabel>
        <relationshipName>Intermediaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant_Scheme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the related grant scheme</description>
        <label>System Scheme Reference No</label>
        <referenceTo>Grant_Scheme__c</referenceTo>
        <relationshipLabel>Intermediaries</relationshipLabel>
        <relationshipName>Intermediaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Intermediary</label>
    <nameField>
        <displayFormat>INT-{00000000}</displayFormat>
        <label>Intermediary Ref No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intermediaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Cabinet office backup/src/classes/AllIntermediaryTriggersHandler.cls
/******************************************************************************************
@Author         Divino Brinas
@Date           09/24/2015
@Project        Cloud Sherpas Cabinet Office Data Source
@Description    Main entry for all the trigger events on Intermediary__c object
*******************************************************************************************/
public without sharing class AllIntermediaryTriggersHandler {
	public static void handleBeforeDelete(Map<Id, Intermediary__c> oldMap){
        Map<Id, Intermediary__c> queriedIntermediaries = new Map<Id, Intermediary__c>([
            SELECT Id, Owner.UserRoleId, Grant_Award__r.Portal_User_Cannot_Delete_This_Record__c, Grant_Scheme__r.Portal_User_Cannot_Delete_This_Record__c
            FROM Intermediary__c
            WHERE Id IN :oldMap.keySet()
        ]);
        for(Intermediary__c intermediaryToCheck : oldMap.values()){
            Intermediary__c queriedIntermediary = new Intermediary__c();
            queriedIntermediary = queriedIntermediaries.get(intermediaryToCheck.id);
            checkUserDepartment(queriedIntermediary, intermediaryToCheck);
            if (queriedIntermediary.Grant_Award__r.Portal_User_Cannot_Delete_This_Record__c
                    || queriedIntermediary.Grant_Scheme__r.Portal_User_Cannot_Delete_This_Record__c) {
                intermediaryToCheck.addError(System.Label.Grant_Intermediary_Delete_Validation_Error_Message);
            }
        }
    }
    private static void checkUserDepartment(Intermediary__c queriedIntermediary, Intermediary__c intermediaryToCheck){
        Boolean isRunningUserRoleDifferentFromOwnerUserRole = UserInfo.getUserType() == Constant.USER_TYPE_COMMUNITY_PLUS && UserInfo.getUserRoleId() != queriedIntermediary.Owner.UserRoleId;
        if(isRunningUserRoleDifferentFromOwnerUserRole){
            intermediaryToCheck.addError(System.Label.User_Delete_Access_Error_Msg);
        }
    }    
}