src/objects/Grant_Award__c.object
<CustomObject>
    <fields>
        <fullName>Allocation_Method__c</fullName>
        <inlineHelpText>The method by which the grant was allocated. This can be either competed, formula, un-competed or criteria based. Definitions of each are given in the Data and System Glossary of Terms, found on the Home page.</inlineHelpText>
        <label>Allocation Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>General Grants - Competed</fullName>
                </value>
                <value>
                    <fullName>General Grants - Un-competed</fullName>
                </value>
                <value>
                    <fullName>General Grants - Criteria Based</fullName>
                </value>
                <value>
                    <fullName>Formula</fullName>
                </value>
                <value>
                    <fullName>Grant in Aid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Award_End_Date__c</fullName>
        <inlineHelpText>The date the grant closes, as per grant award agreement or letter.</inlineHelpText>
        <label>Award End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Award_Start_Date__c</fullName>
        <inlineHelpText>The date the grant was issued, as per grant award agreement or letter.</inlineHelpText>
        <label>Award Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grant_Scheme__c</fullName>
        <description>This is the parent scheme for this award</description>
        <inlineHelpText>This is the System Scheme Reference No and clicking it will take you back to the Scheme that this award belong to.</inlineHelpText>
        <label>Grant Scheme</label>
        <referenceTo>Grant_Scheme__c</referenceTo>
        <relationshipLabel>Grant Awards</relationshipLabel>
        <relationshipName>Grant_Awards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Has_Postal_Code_Been_Checked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates if the postcode has been validated or not</description>
        <label>Has Postal Code Been Checked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Postal_Code_Valid__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox indicates if the value for this post code is valid or not.</description>
        <inlineHelpText>This checkbox indicates if the value for this post code is valid or not.</inlineHelpText>
        <label>Is Postal Code Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Geo_Location__c</fullName>
        <description>This field holds the values for longitude and latitude</description>
        <label>Postal Code Geo Location</label>
        <scale>15</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Parliamentary_Constituency__c</fullName>
        <description>This value is generated automated based on the selected postcode.</description>
        <label>Postal Code Parliamentary Constituency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Region__c</fullName>
        <description>This value is generated automatically based on the selected postal code.</description>
        <label>Postal Code Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Amount_in_funding_agreement__c</fullName>
        <inlineHelpText>For Recipient Type: Organisation. The total amount in pounds of the grant award that was comitted in the grant award agreement.</inlineHelpText>
        <label>Total Amount in funding agreement in GBP</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Grant Award</label>
    <nameField>
        <displayFormat>GA-{000000}</displayFormat>
        <label>System Award Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Awards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Grant_Scheme__c.object
<CustomObject>
    <fields>
        <fullName>Allocation_Method__c</fullName>
        <description>Competed	- e.g. application based
Un-competed 	- e.g. where a charity writes to a Minister about an initiative they have and this aligns with the departmental objectives, so they get given a grant to make that initiative real
Formula 	- where the means by which the money is allocated is calculated through a formula
Criteria Based 	- where there is qualifying criteria in order to receive money, but as long as they qualify, the recipient gets the money, as there is no competition e.g. floods</description>
        <inlineHelpText>The method by which the grant was allocated. This can be either competed, formula, un-competed or criteria based. Definitions of each are given in the Data and System Glossary of Terms, found on the Home page.</inlineHelpText>
        <label>Scheme allocation method</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>General Grants - Competed</fullName>
                </value>
                <value>
                    <fullName>General Grants - Un-competed</fullName>
                </value>
                <value>
                    <fullName>General Grants - Criteria Based</fullName>
                </value>
                <value>
                    <fullName>Formula</fullName>
                </value>
                <value>
                    <fullName>Formula - Criteria Based</fullName>
                </value>
                <value>
                    <fullName>Grant in Aid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Funder__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the funder organisation lookup</description>
        <inlineHelpText>The entity that is funding the grant scheme (this is in most cases, a government department where the funds start)</inlineHelpText>
        <label>Funder</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Is_Funder__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Grant Schemes (Funder)</relationshipLabel>
        <relationshipName>Grant_Schemes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Purpose__c</fullName>
        <description>details can be found on : https://docs.google.com/spreadsheets/d/1Hb7iIacx-Koy2lIrXoqSyzdTf0bh-1TRvCyR8Jwtif8/edit#gid=488764022</description>
        <inlineHelpText>The purpose that the grant is being paid out for. 5 mutually exclusive purposes have been identified. Definitions of each are given in the Data and System Glossary of Terms, found on the Home page. If no option suits, choose None of the above.</inlineHelpText>
        <label>Primary Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Supporting delivery of a public service</fullName>
                </value>
                <value>
                    <fullName>Supporting delivery of a public policy</fullName>
                </value>
                <value>
                    <fullName>Research &amp; Innovation</fullName>
                </value>
                <value>
                    <fullName>Financial Assistance / Support</fullName>
                </value>
                <value>
                    <fullName>Subscriptions and pension payments</fullName>
                </value>
                <value>
                    <fullName>None of the above</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recipient_Sector__c</fullName>
        <description>This is the Scheme&apos;s recipient sector</description>
        <inlineHelpText>Civil Society (Charities, Community Groups, Social enterprise, Communities - Universities are formally charities, so would come under here) - Public Organisations (schools, police, hospitals, libraries)</inlineHelpText>
        <label>Recipient Sector</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Central Government</fullName>
                </value>
                <value>
                    <fullName>Local Government</fullName>
                </value>
                <value>
                    <fullName>Civil Society</fullName>
                </value>
                <value>
                    <fullName>Public Organisations</fullName>
                </value>
                <value>
                    <fullName>Non-Departmental Public Bodies</fullName>
                </value>
                <value>
                    <fullName>Private</fullName>
                </value>
                <value>
                    <fullName>Individuals</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Grant Scheme</label>
    <nameField>
        <displayFormat>SCH-{000000000}</displayFormat>
        <label>System Scheme Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AwardPostalCodeHeatMapController.cls
/******************************************************************************************
@Author         Hamed Izadpanah
@Date           19/02/2016
@Project        Cloud Sherpas Cabinet Office Data Source
@Description    This is the controller for Grant Awards HeatMap functionality
*******************************************************************************************/
public with sharing class AwardPostalCodeHeatMapController {

	@testVisible
	private static String HEAT_MAP_BASE_QUERY_STRING;
	static {
		HEAT_MAP_BASE_QUERY_STRING = 'SELECT Postal_Code_Geo_Location__Latitude__s,';
		HEAT_MAP_BASE_QUERY_STRING += ' Postal_Code_Geo_Location__Longitude__s';
		HEAT_MAP_BASE_QUERY_STRING += ' FROM Grant_Award__c';
		HEAT_MAP_BASE_QUERY_STRING += ' WHERE Is_Postal_Code_Valid__c = true';
		HEAT_MAP_BASE_QUERY_STRING += ' AND Has_Postal_Code_Been_Checked__c = true';
	}

	public Grant_Award__c filterGrantAward {get; private set;}
	public Grant_Scheme__c filterGrantScheme {get; private set;}

	public Decimal mapCurrentZoomRadius {get; set;}
	public Decimal mapCurrentCenterLat {get; set;}
	public Decimal mapCurrentCenterLong {get; set;}

	public Boolean showActiveGrants {get; set;}
	public AwardPostalCodeHeatMapController() {
		mapCurrentZoomRadius = 100;
		mapCurrentCenterLat = 51.50722;
		mapCurrentCenterLong = -0.12750;
		Date startOfThisYearFY = Date.newInstance(Date.today().year(), 4, 1);
		filterGrantAward = new Grant_Award__c(
			Award_Start_Date__c = startOfThisYearFY.addYears(-1),
			Award_End_Date__c = null
		);
		showActiveGrants = true;
		filterGrantScheme = new Grant_Scheme__c();
	}
	private transient Integer foundRecordsCount = null;
	public void checkHeatMapQueryLimit(){
		if(foundRecordsCount == null){
			String queryString = 'SELECT COUNT() FROM Grant_Award__c WHERE Is_Postal_Code_Valid__c = true';
			queryString += ' AND Has_Postal_Code_Been_Checked__c = true';
			queryString += generateQueryConditions();
			foundRecordsCount = Database.countQuery(queryString);
		}
		if(foundRecordsCount > 1000000){
			throw new QueryLimitReachedException(Label.Heatmap_Query_Reached_Limit_Error_Message + ' : ' + String.valueOf(foundRecordsCount));
		}
	}

	public List<SelectOption> getAvailableRegions(){
		List<SelectOption> availableRegionOptions = new List<SelectOption>{
			new SelectOption('', Label.AwardPostalCodeHeatMapAllRegionsLabel)
		};
		List<String> availableRegions = new List<String>();
		for(AggregateResult availableRegion : [
			SELECT Postal_Code_Region__c
			FROM Grant_Award__c
			WHERE Postal_Code_Region__c != null
			GROUP BY Postal_Code_Region__c
		]){
			String foundRegion = (String) availableRegion.get('Postal_Code_Region__c');
			if(String.isNotBlank(foundRegion)){
				availableRegions.add(foundRegion);
			}
		}
		availableRegions.sort();
		for(String availableRegion : availableRegions){
			availableRegionOptions.add(new SelectOption(availableRegion, availableRegion));
		}
		return availableRegionOptions;
	}
	public List<SelectOption> getAvailableConstituencies(){
		List<SelectOption> availableRegionOptions = new List<SelectOption>{
			new SelectOption('', Label.AwardPostalCodeHeatMapAllConstituenciesLabel)
		};
		List<String> availableRegions = new List<String>();
		for(AggregateResult availableRegion : [
			SELECT Postal_Code_Parliamentary_Constituency__c
			FROM Grant_Award__c
			WHERE Postal_Code_Parliamentary_Constituency__c != null
			GROUP BY Postal_Code_Parliamentary_Constituency__c
		]){
			String foundRegion = (String) availableRegion.get('Postal_Code_Parliamentary_Constituency__c');
			if(String.isNotBlank(foundRegion)){
				availableRegions.add(foundRegion);
			}
		}
		availableRegions.sort();
		for(String availableRegion : availableRegions){
			availableRegionOptions.add(new SelectOption(availableRegion, availableRegion));
		}
		return availableRegionOptions;
	}

	public String generateQueryConditions(){
		String generatedConditions = '';
		if(showActiveGrants){
			generatedConditions += ' AND Award_Start_Date__c <= ' + String.valueOf(Date.today());
			generatedConditions += ' AND (';
			generatedConditions += ' Award_End_Date__c = null';
			generatedConditions += ' OR Award_End_Date__c >= ' + String.valueOf(Date.today());
			generatedConditions += ')';
		}
		if(!showActiveGrants && filterGrantAward.Award_Start_Date__c != null){
			generatedConditions += ' AND Award_Start_Date__c >= ' + String.valueOf(filterGrantAward.Award_Start_Date__c);
		}
		if(!showActiveGrants && filterGrantAward.Award_End_Date__c != null){
			generatedConditions += ' AND Award_End_Date__c <= ' + String.valueOf(filterGrantAward.Award_End_Date__c);
		}
		if(String.isNotBlank(filterGrantAward.Postal_Code_Region__c)){
			generatedConditions += ' AND Postal_Code_Region__c = \'' + filterGrantAward.Postal_Code_Region__c + '\'';
		}
		if(String.isNotBlank(filterGrantAward.Allocation_Method__c)){
			generatedConditions += ' AND Allocation_Method__c = \'' + filterGrantAward.Allocation_Method__c + '\'';
		}
		if(String.isNotBlank(filterGrantAward.Postal_Code_Parliamentary_Constituency__c)){
			generatedConditions += ' AND Postal_Code_Parliamentary_Constituency__c = \'' + filterGrantAward.Postal_Code_Parliamentary_Constituency__c + '\'';
		}
		if(String.isNotBlank(filterGrantScheme.Funder__c)){
			generatedConditions += ' AND Grant_Scheme__r.Funder__c = \'' + filterGrantScheme.Funder__c + '\'';
		}
		if(String.isNotBlank(filterGrantScheme.Primary_Purpose__c)){
			generatedConditions += ' AND Grant_Scheme__r.Primary_Purpose__c = \'' + filterGrantScheme.Primary_Purpose__c + '\'';
		}
		if(String.isNotBlank(filterGrantScheme.Recipient_Sector__c)){
			generatedConditions += ' AND Grant_Scheme__r.Recipient_Sector__c = \'' + filterGrantScheme.Recipient_Sector__c + '\'';
		}
		return generatedConditions;
	}

	public void setNewMapCenter(){
	}

	public List<Grant_Award__c> queryGrantAwards(){
		List<Grant_Award__c> foundGrantAwards = new List<Grant_Award__c>();
		String generatedQueryString = HEAT_MAP_BASE_QUERY_STRING + generateQueryConditions();
		try{
			checkHeatMapQueryLimit();
			foundGrantAwards = Database.query(generatedQueryString);
		}catch(Exception exceptionToHandle){
			ApexPages.addMessages(exceptionToHandle);
		}
		return foundGrantAwards;
	}

	public String getHeatMapPoints(){
		String returnValue = '[';
		for(Grant_Award__c grantAwardToAdd : queryGrantAwards()){
			returnValue += 'new google.maps.LatLng(' + grantAwardToAdd.Postal_Code_Geo_Location__Latitude__s + ',' + grantAwardToAdd.Postal_Code_Geo_Location__Longitude__s + '),';
		}
		returnValue += ']';
		return returnValue;
	}

	public AggregateResult getLocationBasedSummary(){
		AggregateResult returnValue;
		String queryString = 'SELECT SUM(Total_Amount_in_funding_agreement__c) awardsAmount, COUNT(Id) awardsCount';
		queryString += ' FROM Grant_Award__c';
		queryString += ' WHERE DISTANCE(Postal_Code_Geo_Location__c, GEOLOCATION(:mapCurrentCenterLat, :mapCurrentCenterLong), \'mi\') < :mapCurrentZoomRadius';
		queryString += generateQueryConditions();
		try{
			checkHeatMapQueryLimit();
			returnValue = Database.query(queryString);
		} catch (Exception exceptionToHandle){
			ApexPages.addMessages(exceptionToHandle);
		}
		return returnValue;
	}

	public List<AggregateResult> getAllRegionTotalAmounts(){
		List<AggregateResult> returnValue;
		String queryString = 'SELECT Postal_Code_Region__c, SUM(Total_Amount_in_funding_agreement__c) awardsAmount';
		queryString += ' FROM Grant_Award__c';
		queryString += ' WHERE DISTANCE(Postal_Code_Geo_Location__c, GEOLOCATION(:mapCurrentCenterLat, :mapCurrentCenterLong), \'mi\') < :mapCurrentZoomRadius';
		queryString += generateQueryConditions();
		queryString += ' GROUP BY Postal_Code_Region__c';
		queryString += ' ORDER BY Postal_Code_Region__c';
		try{
			checkHeatMapQueryLimit();
			returnValue = Database.query(queryString);
		} catch (Exception exceptionToHandle){
			ApexPages.addMessages(exceptionToHandle);
		}
		return returnValue;
	}

	public class QueryLimitReachedException extends Exception{}

}