src/objects/Grant_Scheme__c.object
<CustomObject>
    <fields>
        <fullName>Duration__c</fullName>
        <description>The Scheme&apos;s duration</description>
        <inlineHelpText>How long the scheme will run for. The duration is from the scheme opening to the last grants ending.</inlineHelpText>
        <label>Duration (years)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <formula>DATE(YEAR(Start_Date__c) + VALUE(TEXT(Duration__c)),MONTH(Start_Date__c),DAY(Start_Date__c))-1</formula>
        <inlineHelpText>This field is auto-calculated based on the start date and the duration. Needed when running reports.</inlineHelpText>
        <label>Scheme end date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Financial_Year_Multi__c</fullName>
        <label>Scheme financial year</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Financial_Year</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>The date the Grant Scheme commences</inlineHelpText>
        <label>Scheme start date</label>
        <type>Date</type>
    </fields>
    <label>Grant Scheme</label>
    <nameField>
        <displayFormat>SCH-{000000000}</displayFormat>
        <label>System Scheme Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grant Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FYcal.cls
/******************************************************************************************
@Author         Daniel Lagar
@Date           26/10/2016
@Project        Cloud Sherpas Cabinet Office Data Source
@Description    Trigger to calculate the Financial Year of Grant Schemes
*******************************************************************************************/
Public Class FYcal{ 
    public static void FinancialYear(list<Grant_Scheme__c> piNewList){
        For(Grant_Scheme__c GS : piNewList){
            If(gs.End_Date__c == NULL){
                continue;
            }
            string strFY = '';
            string strSD = '';
            string strED = '';
            string strSDyear = '';
            string strEDyear = '';
            integer intSD = 0;
            integer intED = 0;
            integer intSDyear = 0;
            integer intEDyear = 0;
            integer intDuration = 0;
            intSD = GS.Start_Date__c.year();
            intED = GS.End_Date__c.year();
            
            strSD = string.valueOf(intSD);
            strED = string.valueOf(intED);
            strSDyear = strSD.mid(2, 2);
            strEDyear = strED.mid(2, 2);
            intSDyear = integer.valueOf(strSDyear);
            intEDyear = integer.valueOf(strEDyear);
            intDuration = integer.valueOf(gs.Duration__C);
            
            system.debug('intSD   ' + intSD);
            system.debug('intED   ' + intED);
            system.debug('GS start date       ' + GS.Start_Date__c.format());
            
            date dt = date.valueOf('1914-12-31');
            If(GS.Start_Date__c <= dt){
                system.debug('im here');
                strFY = 'FY 14/15';
            }
            Else{
                For(Integer i = 0; i < intDuration; i++){
                   
                   
            
                    system.debug('Start_Date__c    ' + GS.Start_Date__c + '     ' +  GS.Start_Date__c.month());
                    system.debug('End Date    ' + GS.End_Date__c + '     ' +  GS.End_Date__c.month());
                    
                If(i == intED && GS.End_Date__c.month() < 4 && GS.Start_Date__c.month() >= 4){
                        
                        break;
                    }
                    
                    If(GS.Start_Date__c.month() >= 4 && GS.End_Date__c.month()<=12){
                        If(strSD == '1999'){
                            strFY = strFY + 'FY ' + string.valueOf(intSDyear) + '/' + '00' + ';';
                        }
                        Else {
                            strFY = strFY + 'FY ' + string.valueOf(intSDyear) + '/' + string.valueOf((intSDyear+1)) + ';'; 
                        }
                        
                    }
                    Else If(GS.Start_Date__c.month() < 4 && GS.End_Date__c.month()<=12){
                        If(strSD == '1999'){
                            strFY = strFY + 'FY ' + string.valueOf(intSDyear) + '/' + '00' + ';';
                        }
                        Else{
                            strFY = strFY + 'FY ' + string.valueOf((intSDyear-1)) + '/' + string.valueOf(intSDyear) + ';'; 
                        }
                        
                    }
                   intSDyear++; 
                }
            }
            system.debug('String FY    ' + strFY);
            gs.Financial_Year_Multi__c = strFY;
        }
     }
}