src/objects/Programme__c.object
<CustomObject>
    <description>This is the Grant programme.</description>
    <fields>
        <fullName>Portal_User_Cannot_Delete_This_Record__c</fullName>
        <formula>AND( 
 NOT($Setup.Bypass__c.Validation_Rules__c) 
 , NOT($Setup.Bypass__c.Business_Rules_for_Edit_and_Delete__c)
 , ISPICKVAL($Profile.UserType, &apos;PowerCustomerSuccess&apos;) 
 , (TODAY() - DATEVALUE(CreatedDate) ) &gt; 2 
)</formula>
        <label>Portal User Cannot Delete This Record</label>
        <type>Checkbox</type>
    </fields>
    <label>Grant Programme</label>
    <nameField>
        <label>Programme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grant Programmes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CabinetOffice/src/classes/AllProgrammeTriggersHandler.cls
/******************************************************************************************
@Author         Divino Brinas
@Date           09/24/2015
@Project        Cloud Sherpas Cabinet Office Data Source
@Description    Main entry for all the trigger events on Programme__c object
*******************************************************************************************/
public without sharing class AllProgrammeTriggersHandler {
    public static void handleBeforeDelete(Map<Id, Programme__c> oldMap){
        Map<Id, Programme__c> queriedProgrammes = new Map<Id, Programme__c>([
            SELECT Id, Owner.UserRoleId, Portal_User_Cannot_Delete_This_Record__c
            FROM Programme__c
            WHERE Id IN :oldMap.keySet()
        ]);
        for(Programme__c programmeToCheck : oldMap.values()){
            Programme__c queriedProgramme = new Programme__c();
            queriedProgramme = queriedProgrammes.get(programmeToCheck.id);
            checkUserDepartment(queriedProgramme, programmeToCheck);
            if (queriedProgramme.Portal_User_Cannot_Delete_This_Record__c){
                programmeToCheck.addError(System.Label.Grant_Programme_Delete_Validation_Error_Message);
            }
        }
    }
    private static void checkUserDepartment(Programme__c queriedProgamme, Programme__c programmedToCheck){
        Boolean isRunningUserRoleDifferentFromOwnerUserRole = UserInfo.getUserType() == Constant.USER_TYPE_COMMUNITY_PLUS && UserInfo.getUserRoleId() != queriedProgamme.Owner.UserRoleId;
        if(isRunningUserRoleDifferentFromOwnerUserRole){
            programmedToCheck.addError(System.Label.User_Delete_Access_Error_Msg);
        }
    }
}